### ISSUE TITLE
HTML Tags are posted from excerpt

### ISSUE THREAD

**Issue by thisisTQ** [pfefferle/wordpress-activitypub#10]
When the excerpt is used by the plugin and utilized in a post, this results in paragraph tags being added before and after the excerpt, along with line breaks (if there are any in the excerpt.)

**Comment by pfefferle** [comment]
is there a prefered way? removing the HTML and/or the "\n"s ?

**Comment by thisisTQ** [comment]
I'd say preferred is to remove all HTML. I don't know how it is with other platforms that use activity hub as protocol, but on Mastodon HTML simply isn't parsed.
