### ISSUE TITLE
ability to follow all articles like in Pterotype: @blog@domain.com

### ISSUE THREAD

**Issue by rebelcode-xr** [pfefferle/wordpress-activitypub#100]
coming from [Pterotype](https://github.com/pterotype-project/pterotype) (which sadly seems dead) I expected to find all articles in @blog@domain.com but it seems not to be the case here.

I found out (documentation doesn't explain it) that instead your plugin works with WP usernames: @username@domain.com 
Do you plan to add this function? In this case would be also nice to have a "choose avatar" option.

I really hope this project will get more features soon 🙏

**Comment by pfefferle** [comment]
There is already an issue for that, so I will close this: https://github.com/pfefferle/wordpress-activitypub/issues/43

But yes, it is on my list :)
