### ISSUE TITLE
Federation weirdness -- posts totally unrelated to articles showing up in the comments feed

### ISSUE THREAD

**Issue by shebang79** [pfefferle/wordpress-activitypub#101]
So..

This might be an edge case, but my domain name used to be a Mastodon server. I shut that down later on, then re-used the domain for a WP server. But for some reason its acting like its following people. So there are literally thousands of "comments" that show up that aren't attached to an article, all waiting for approval. My wordpress account isn't mentioned in their posts at all, its pretty strange. Like.. its acting as if my wordpress is following their accounts.

**Comment by pfefferle** [comment]
Oh! This is really an edge case. It seems that you still receive Posts that other AP plattforms sees as relevant for your server. I never thought about that case, so my plugin is accepting all of these, without checking if they are really relevant. :(

**Comment by shebang79** [comment]
I have a knack for finding all the best edge cases, haha!
