### ISSUE TITLE
Feature request: Publish Podlove episodes like articles to followers

### ISSUE THREAD

**Issue by thomham** [pfefferle/wordpress-activitypub#102]
Currently the episodes published via Podlove podcast plugin are not pushed to the followers.
Since episodes are also like articles readable entities, followers are interested to see them when published by the followed user.

One could also think of making it configurable. But this could come later.

**Comment by pfefferle** [comment]
Have you enabled the podlove post type in the settings?

**Comment by thomham** [comment]
OMG, I am blind?! Is this new in the new version I just upgraded or was this already in the 0.10 version?. Lets see, tomorrow the next episode is published. Expect a mention on Mastodon when it works. Thanks for the hint. I will close the issue then.
Thank you so much. :-)

**Comment by pfefferle** [comment]
This was also part of 0.10.0 :)

**Comment by thomham** [comment]
Field test successful. Closing the none-isssue.

**Comment by pfefferle** [comment]
nice :)
