### ISSUE TITLE
Mastodon follows permanently stuck pending response

### ISSUE THREAD

**Issue by jgoerzen** [pfefferle/wordpress-activitypub#106]
Mastodon follows of this system are permanently stuck pending a response ("cancel follow request" show up in Mastodon).  Also, although it seems like it worked at least once, there is a lack of continuity of followers receiving new posts.

Background on this is here: https://mstdn.social/@feditips/105340310490376047

I would be happy to help do whatever I can to debug this.

**Comment by jgoerzen** [comment]
There are some other users with similar symptoms here: https://wordpress.org/support/topic/mastodon-approve-follow-request/

**Comment by jgoerzen** [comment]
I can confirm that the patch in #105 fixes this!  Thanks @mediaformat

**Comment by jgoerzen** [comment]
Closing due to merged #105

**Comment by kupietools** [comment]
This appears to be a live issue again. I am having the exact problem described, with the latest version of the plugin.

**Comment by pfefferle** [comment]
@kupietools maybe this helps https://blog.rac.me.uk/2022/11/10/activitypub-for-wordpress-how-to-fix-modsecurity-to-make-it-work/
