### ISSUE TITLE
featured image

### ISSUE THREAD

**Issue by anchelnl** [pfefferle/wordpress-activitypub#108]
Would be nice to have to add featured image as a template placeholder.

**Comment by pfefferle** [comment]
I can do so, but the problem is, that some instances, like mastodon for example, does not support inline images.

**Comment by tiotrom** [comment]
I was about to ask the same... :D. Too bad Mastodon doesn't support that, but you can add a disclaimer besides that placeholder.

**Comment by regenpfeifer** [comment]
I would like to support the option to add featured images from WordPress with placeholders, as discussed here: https://friends.regenpfeifer.net/display/d368d644-215f-f9bf-7323-f19894753464
