### ISSUE TITLE
Update edited comments

### ISSUE THREAD

**Issue by tiotrom** [pfefferle/wordpress-activitypub#109]
If someone leaves a comment from say Friendica, then later on edits it, would it update the comment on WP?

**Comment by mediaformat** [comment]
This is an interesting case, as the plugin sends Update activities as well.

WP core doesn't create Comment revisions, there is also no `updated at` time.

To permit updates would be possible but should probably follow the selected Comment moderation settings: 
￼￼￼
- If the comment is in moderation then update.
- If the comment is already approved, perhaps the updated comment would return to ´hold´ status.

**Comment by mediaformat** [comment]
> So it cannot update the comment while published and keep it published?

It could. The question is how to do it in a transparent manner, to prevent abuse, and not open a backdoor to spam.

**Comment by mediaformat** [comment]
In terms of visibility for received Fediverse comments, one way to represent that an edit has happened could be to use native html elements `<del>` for the previous comment and `<ins>` for the new one, this would also allow themes the ability to style or even hide previous elements.
