### ISSUE TITLE
503 remote SSL certificate could not be verified

### ISSUE THREAD

**Issue by novadeviator** [pfefferle/wordpress-activitypub#11]
When trying to subscribe to @username@domain.tld on mastodon (mastodon.art) I get the error:

    503 Remote SSL certificate could not be verified.

This happens also when I do http://domain.tld/author/username. But when I do https://domain.tld/author/username I get 0 results.

How can I test more?

**Comment by pfefferle** [comment]
Can you give me the correct URLs that I can try to reproduce it?

**Comment by novadeviator** [comment]
yes, it's https://lukaprincic.si/author/luka

**Comment by SuperSandro2000** [comment]
Maybe it is an ssl issue?
see https://github.com/tootsuite/mastodon/issues/6449

**Comment by danicotillas** [comment]
I'm having this very same problem on @danicotilas@comunicacionabierta.net
Any ideas?

**Comment by pfefferle** [comment]
@danicotillas it seems to be a different issue... the well-known URI is not set: https://webfinger.net/lookup/?resource=mailto%3Adanicotilas%40comunicacionabierta.net Do you use NGINX?

**Comment by danicotillas** [comment]
Yes, I do.
I'm hosted on Siteground

**Comment by pfefferle** [comment]
OK, then the permalinks may not be generated properly. Maybe this thread helps https://github.com/pfefferle/wordpress-activitypub/issues/8
