### ISSUE TITLE
post titles with links

### ISSUE THREAD

**Issue by regenpfeifer** [pfefferle/wordpress-activitypub#110]
This is really a great plugin with already a lot of formatting options. It would be great to offer the option to add post titles with links to the original posting. Cf. my comment here: https://friends.regenpfeifer.net/display/d368d644-215f-f9bf-7323-f19894753464, maybe you could add a placeholder which supports something like this: <a href="%permalink%">%title%</a>

**Comment by pfefferle** [comment]
You can do this right now like: `<strong><a href="%permalink%">%title%</a></strong>` for example!

Does that work for you?

**Comment by pfefferle** [comment]
Oops, that does not work actually, because it generates HTML code. I will add that function, thanks for the reporting!

**Comment by regenpfeifer** [comment]
Thank you very much, @pfefferle, I am looking forward to using this new function!
