### ISSUE TITLE
Only one user

### ISSUE THREAD

**Issue by botsonthego** [pfefferle/wordpress-activitypub#112]
At the moment only the owner of the site has a federated username botsonthego@botsonthego.xyz and this is the only one that will post to federated site when they post

I want to have more users or all my users to have a username@botsonthego.xyz for federation because I have a person on the site that writes our blog posts, and even if they can't have there own username but have the main username show the posts when they post

is this possible and if so how do I set it up please

**Comment by pfefferle** [comment]
For more context: https://github.com/pfefferle/wordpress-ostatus/issues/13

**Comment by botsonthego** [comment]
sorry I did not realise you created this as well so so I put the same message

**Comment by botsonthego** [comment]
so as discussed my host is currently looking into the JSON being broken 

"name": "",
  "summary": "",
  "preferredUsername": "",
  "url": "https:\/\/botsonthego.xyz\/author\/",

and I hope that is and when its fixed the plugin should work correctly for mastodon

**Comment by pfefferle** [comment]
It is really hard to tell, because it seems temporary and seems to be no general problem. One account works one not.

**Comment by botsonthego** [comment]
yes it is strange

**Comment by pfefferle** [comment]
can you post a list with all plugins you use?

**Comment by botsonthego** [comment]
ActivityPub
ActivityStream extension
Akismet Anti-Spam
Broken Link Checker
Classic Editor
Companion Auto Update
host-meta 
Imagify
IndieAuth
IndieWeb
Jetpack by WordPress.com
Micropu
NodeInfo
One Click Demo Import 
OneSignal Push Notifications
OStatus
Post Kinds
Preloader Plus
PWA for WP
Salmon
Simple Location
Site Kit by Google
Syndication Links
UpdraftPlus - Backup/Restore
WebFinger
Webmention
WebSub/PubSubHubbub
Wordfence Security
WordProof Timestamp
WP Rocket
Yoast SEO Premium
