### ISSUE TITLE
Don't set `to` field to receiving user id for each user on federation

### ISSUE THREAD

**Issue by lambadalambda** [pfefferle/wordpress-activitypub#114]
https://github.com/pfefferle/wordpress-activitypub/blob/b49cc5333cce42638d4e1b8f9aae3a16c5bd8b6f/includes/class-activity-dispatcher.php#L34

The `to` field should contain the wordpress user's follower collection, as putting a user into the `to` field is treated like a direct mention, so it will generate notifications.

See https://git.pleroma.social/pleroma/pleroma/-/issues/2480#note_81046

**Comment by pfefferle** [comment]
OK, maybe I misread:

> Origin servers sending publicly addressed activities to sharedInbox endpoints MUST still deliver to actors and collections otherwise addressed (through to, bto, cc, bcc, and audience) which do not have a sharedInbox and would not otherwise receive the activity through the sharedInbox mechanism.

**Comment by pfefferle** [comment]
@lambadalambda ah, I see the issue! I have to use a collection instead of a single user and the actor url instead of the inbox, right?

**Comment by pfefferle** [comment]
OK, I checked again, and this is always a collection. It might be that there is only one in the collection, but it is always a collection: https://github.com/pfefferle/wordpress-activitypub/blob/b49cc5333cce42638d4e1b8f9aae3a16c5bd8b6f/includes/functions.php#L202

**Comment by pfefferle** [comment]
...or should the list empty and the server is handling all the inbox stuff?

**Comment by mediaformat** [comment]
@lambadalambda you are correct, I had corrected this in an upstream feature branch, but I will submit a PR for this shortly.

**Comment by mediaformat** [comment]
@lambadalambda I wonder if there is some MRF on the receiving instance causing this issue. I am currently testing with a vanilla pleroma and it is not triggering notifications

**Comment by rinpatch** [comment]
Maybe you are testing with old Pleroma. We used to not generate notifications if there is no explicit mention in the `tag` field, but this behavior was lost to some refactorings unfortunately

**Comment by lambadalambda** [comment]
Actually I think the error is on our side because we add a user to the `to` collection if the message arrives in their own inbox and not the shared inbox. Will have to check that.
