### ISSUE TITLE
Only first "level" of toots are added as comments

### ISSUE THREAD

**Issue by ldidry** [pfefferle/wordpress-activitypub#116]
Let’s have a little schema to explain:
```
Initial toot in Mastodon
├── reply level 1
│   └── reply level 2
└── other reply level 1
```

Only the "level 1" toots are added to Wordpress as comments. In the past, other levels were added as comments without parent comment or parent post, which was annoying but I could re-attach them to the right post and parent comment, now they don’t appear in Wordpress.

**Comment by mediaformat** [comment]
This is a known issue, and will be fixed in an upcoming release, along with federated replies

**Comment by pfefferle** [comment]
> In the past, other levels were added as comments without parent comment or parent post, which was annoying but I could re-attach them to the right post and parent comment, now they don’t appear in Wordpress.

Yes, I changed that, because it creates a lot of inconsistencies, because it also added direct messages and global timeline items.

**Comment by juengling** [comment]
(Sorry for using this issue as a discussion board, but I couldn't find another better way.)

> Only the "level 1" toots are added to Wordpress as comments.

Can anybody explain to me how I can make this work? Following Wordpress from e.g. Mastodon is possible, but no Mastodon comment finds its way back to Wordpress.
