### ISSUE TITLE
Wordpress plugins should be licensed as GPLv2 or later

### ISSUE THREAD

**Issue by terenc3** [pfefferle/wordpress-activitypub#119]
See https://wordpress.org/about/license/ and https://wordpress.org/plugins/developers/

> Your plugin must be compatible with the GNU General Public License v2, or any later version. We strongly recommend using the same license as WordPress — “GPLv2 or later.

**Comment by pfefferle** [comment]
The MIT license is GPL compatible, so I see no problem to keep MIT. The plugin was also reviewed by the plugins team and they had no problems with the license.

**Comment by pfefferle** [comment]
@terenc3 Do you have any concerns with MIT in general?

**Comment by terenc3** [comment]
No i don't have any concerns. I just read some license stuff and came across the WordPress licensing requirements. At first it was not clear to me, that a compatible license works to, but its fine
