### ISSUE TITLE
Can't follow from Pixelfed

### ISSUE THREAD

**Issue by rebelcode-xr** [pfefferle/wordpress-activitypub#134]
Pixelfed federation doesn't seems to work, no problems with Mastodon and MissKey.

- I can find the profile from Pixelfed
- I click "follow" and I get confirmation:
![image](https://user-images.githubusercontent.com/63522951/147120131-e6f4118a-8537-4fa4-b594-a8eb28984e9f.png)
![image](https://user-images.githubusercontent.com/63522951/147119865-f24a9f3e-dc26-4a82-919e-dfa779d627ed.png)
- I cannot see the Pixelfed profile in the WordPress Followers page
- I don't get any update on new WP posts in Pixelfed

**Comment by lapineige** [comment]
Do you see (non WP) post for other accounts ?
In my case I have trouble with a lot of them (if non-Pixelfed account, but not only), so I would suspect a Pixelfed federation issue (we are used to it :/).

**Comment by mediaformat** [comment]
Looks like a Pixelfed issue https://github.com/pixelfed/pixelfed/issues/3050

**Comment by rebelcode-xr** [comment]
> Maybe related to this Pixelfed issue [pixelfed/pixelfed#3050](https://github.com/pixelfed/pixelfed/issues/3050)

Let's see if their fix solves the issue, thanks! 😁

**Comment by rebelcode-xr** [comment]
it might also be connected to this:
https://github.com/pixelfed/pixelfed/issues/3167
