### ISSUE TITLE
`Create` and `Note` should not have the same ActivityPub ID

### ISSUE THREAD

**Issue by alexgleason** [pfefferle/wordpress-activitypub#135]
Hi, I'm working on a Pleroma issue to combine activities and objects into one table in the database: https://git.pleroma.social/pleroma/pleroma/-/merge_requests/3571

When running the migration, I'm getting conflicts:

![Screenshot from 2021-12-30 10-33-24](https://user-images.githubusercontent.com/3639540/147770587-6974b7b5-43de-48f6-929e-3156ec9743a5.png)

It's because the `Create` activity and the `Note` object have the same ActivityPub ID, which is not valid in ActivityPub.

I'm planning to drop these activities in the migration.

**Comment by pfefferle** [comment]
good point! thanks for the ping!
