### ISSUE TITLE
PHP Warning about trim

### ISSUE THREAD

**Issue by artlung** [pfefferle/wordpress-activitypub#136]
PHP Warning:  trim() expects at least 1 parameter, 0 given in wp-content/plugins/activitypub/templates/blog-json.php on line 41

```
$json->publicKey = array(
	'id' => \get_home_url( '/' ) . '#main-key',
	'owner' => \get_home_url( '/' ),
	'publicKeyPem' => \trim(),
);
```
Line 41 is `'publicKeyPem' => \trim(),`

**Comment by pfefferle** [comment]
Oh, I wasn't aware, that it is loaded anywhere. This is work in progress... I will have a look, where it will be called.

**Comment by pfefferle** [comment]
Keep!
