### ISSUE TITLE
Anyway to get featured image as an option?

### ISSUE THREAD

**Issue by chrisbulow** [pfefferle/wordpress-activitypub#146]
I don’t think this is available unless I’ve missed something but being able to ensure the featured image also posts to Mastodon would be great. Thanks.

**Comment by pfefferle** [comment]
The featured image will be added as attachement. Sadly mastodon does not show inline/html images and attachements only if you use the "note" activity type.

**Comment by chrisbulow** [comment]
Many thanks for responding so quickly. Appreciated.
