### ISSUE TITLE
Comments don't appear to work properly

### ISSUE THREAD

**Issue by wizzwizz4** [pfefferle/wordpress-activitypub#15]
I had a little look at [this post](https://fosstodon.org/web/statuses/101404814357731423) and posted a comment... only to see ~~[this monstrosity](https://blog.jabberhead.tk/2019/01/12/join-the-fediverse/#comments)~~ no longer exhibits problem.

It appears that, instead of displaying the comment body, it calls me Anonymous and displays a link to my user profile instead. I'd wager that this is not the expected behaviour.

**Comment by vanitasvitae** [comment]
Yeah, I was wondering about the profile links as well. For now I deleted those links manually (that's why the link is gone). Are the links used for something internally?

**Comment by pfefferle** [comment]
These are likes and boosts... will deactivate it, until I have implemented a better UI.
