### ISSUE TITLE
Can't follow from Hubzilla

### ISSUE THREAD

**Issue by hikerus** [pfefferle/wordpress-activitypub#161]
I tried with two different WP installations with AcitvityPub plugin installed and I am not able to follow from a Hubzilla instance (version 7.6.1 - 1253) - "channel not found".
First WP installation in in root directory of a domain, second WP installation is in subdirectory /wp of a domain. There I added the web-finger configuration in .htaccess.

**Comment by pfefferle** [comment]
Does the hubzilla instance has the activitypub feature enabled? This seems not be active on all instances I tested so far.

**Comment by hikerus** [comment]
Of course - it federates with Pixelfed and Writefreely without any problems.

**Comment by pfefferle** [comment]
An you send me the server URL? Is it a public server so I can create a test account?

**Comment by hikerus** [comment]
Blog URL is https://hiker.tips . Hubzilla server is closed - so I can make you a test account. Any DM to send you user/pw?

**Comment by hikerus** [comment]
btw 
Would be very grateful if issue #151 could be solved at first - to follow the WP account is possible but the posts in WP are not displayed in the TL of #Pleroma.

**Comment by hikerus** [comment]
Made more test and I found the the plugin works with #Hubzilla. There the connection to the WordPress blog should be added in "Connections - Add" - then it works.
