### ISSUE TITLE
I cannot see my profile or post in Mastodon

### ISSUE THREAD

**Issue by wergin** [pfefferle/wordpress-activitypub#163]
Hello
I have the plugin acitivitypub installed today.
I wrote a post in my blog.
Then I seach my name @ANDINI@www.andi-net.de in Mastodon but nothing is shown to me.
I seach for my post, but nothing is shown to me.
The Blog is: www. andi-net.de/p/
What do I wrong?

**Comment by pfefferle** [comment]
Your blog seems to be in a subfolder and that does not work out of the box. See: https://github.com/pfefferle/wordpress-activitypub/issues/37

**Comment by mediaformat** [comment]
There is a 404 error in the redirect: 
https://www.andi-net.de/.well-known/webfinger?resource=acct:ANDINI@www.andi-net.de leads to 
https://www.andi-net.de/anet/p/.well-known/webfinger?resource=acct:ANDINI@www.andi-net.de

**Comment by wergin** [comment]
Hello
Thanks for Helping
I don't know why there is a 404.
I deleted all now.
I will try once more without this domain and a subfolder next time.

**Comment by wergin** [comment]
Hello
I have now once more all installed, in one subfolder. (not the same like in the posts above)
I do put the htaccess in the root and in www, where the subfolder is.
If I use webfinger I have a 404.
I don't know why.
In Mastodon find me not.

**Comment by pfefferle** [comment]
Can you share your config and the URLs and profile URLs, so that we can have a look?

**Comment by wergin** [comment]
Hello, thank you for answer.
The URL is: andi-net.de 
The profile URL is: https://andi-net.de/author/andini/
Do you mean the config-file of Wordpress?

**Comment by pfefferle** [comment]
Ah, now you do not use a subfolder! The WebFinger endpoint does not return anything https://webfinger.net/lookup/?resource=andini%40andi-net.de

**Comment by wergin** [comment]
Doch, I use a subfolder in the www-root

**Comment by wergin** [comment]
In Mastdon I am not to see

**Comment by wergin** [comment]
https://andi-net.de/xanet/.well-known/webfinger?resource=acct:ANDINI@www.andi-net.de

**Comment by wergin** [comment]
I have fixed with help of the site: https://wordpress.org/support/article/giving-wordpress-its-own-directory/

Now Mastodon find me!!! :-)

Thank you very mutch and for your 

patience with my :-)

**Comment by wergin** [comment]
Now I habe fixed with help of the site: https://wordpress.org/support/article/giving-wordpress-its-own-directory/

Now Mastodon find me :-)

Thank you for your help an your patience with me :-)

Solved

**Comment by wergin** [comment]
Now I habe fixed with help of the site: https://wordpress.org/support/article/giving-wordpress-its-own-directory/

Now Mastodon find me :-)

Thank you for your help an your patience with me :-)

Solved

**Comment by wergin** [comment]
Now I habe fixed with help of the site: https://wordpress.org/support/article/giving-wordpress-its-own-directory/

Now Mastodon find me :-)

Thank you for your help an your patience with me :-)

Solved

**Comment by wergin** [comment]
i have fixed with help of the site: https://wordpress.org/support/article/giving-wordpress-its-own-directory

Now Mastodon find me :-)

Thank you for helping and patience with me :-)

**Comment by wergin** [comment]
Now I habe fixed with help of the site: https://wordpress.org/support/article/giving-wordpress-its-own-directory/

Now Mastodon find me :-)

Thank you for your help an your patience with me :-)

**Comment by pfefferle** [comment]
But both URLs do not work! You should get (at least) the target version fixed before you try to redirect the main folder.

Have you installed multiple WordPress'?

**Comment by wergin** [comment]
Now I habe fixed with help of the site: https://wordpress.org/support/article/giving-wordpress-its-own-directory/

Now Mastodon find me :-)

Thank you for your help an your patience with me :-)

**Comment by wergin** [comment]
I have no multiple wordpress.
The URL andi-net.de I can see in my browser.
The wordpress is in subfolder xanet
xanet is in www-root.
The code in the htaccess is `RedirectMatch "^\/\.well-known(.*)$" "\/xanet\/\.well-known$1"`
Where have I what to fix?
