### ISSUE TITLE
What is the future of the plugin?

### ISSUE THREAD

**Issue by Bennneeeet** [pfefferle/wordpress-activitypub#166]
Hi 👋  

First of all, thanks for the development of the plugin so far!

What is the future of the plugin?
There doesn't seem to be much activity here at the moment. However, many people would like to see further development. Are there plans to move forward in the future or is there currently not enough time or interest?

It would be a shame if no further development would take place, because the Fediverse is currently experiencing a massive run, so WordPress blogs could be filled with new life again.

Please share your plans with us and tell us if and how you can support.

Best regards

**Comment by pfefferle** [comment]
There is further development, @mediaformat currently works on a big pull request to fully support comment federation. But it is still a small spare time project with only a handful of contributors.

**Comment by pfefferle** [comment]
Btw. here is the plan https://github.com/pfefferle/wordpress-activitypub/projects?type=classic

😊

**Comment by Bennneeeet** [comment]
Thank you for your reply. The work of @mediaformat I had not on the screen. 

Looking forward to future developments. Maybe I can contribute something as well, we'll see.

Thanks. ✌️
