### ISSUE TITLE
Give max. Characters used for a a status

### ISSUE THREAD

**Issue by jaschaurbach** [pfefferle/wordpress-activitypub#168]
Very long posts are quite a mess on Mastodon or on pixelfed - especially when you are on mobile. I know, I could use %excerpt% but 400 chars are too few and I want to use the %excerpt% for other platforms. 

It would be great if we could get a new placeholder like %userdefinedlenght% or whatever where I can set the number of characters to whatever I like. Shorter posts will be completely shown, longer posts will be cut. 

What do you think?

**Comment by pfefferle** [comment]
This is now possible with `[ap_excerpt length="200"]`, where the length can be anything you want!
