### ISSUE TITLE
Cannot follow - webfinger appears ok

### ISSUE THREAD

**Issue by mark4409** [pfefferle/wordpress-activitypub#17]
I've installed the activitypub plugin and activated. I'm on wordpress 4.98 using PHP 7.2. 

When I try and add contact hillexplorer@hillexplorer.com from friendica, I get the message 'network type couldn't be detected. Contact not added'. This is with the latest RC of friendica with ActivityPub support. 

Webfinger tests appear to be ok

**Comment by mark4409** [comment]
I cannot follow using the author url as friendica automatically follows the rss feed rather than use activity pub if I do that.

**Comment by mark4409** [comment]
Update: Also tested with Mastodon and pleroma, and I am unable to find hillexplorer@hillexplorer.com

Is there some other step I need to perform? Please advise.

**Comment by pfefferle** [comment]
The profile URLs do not return the JSON profile if you add the `application/json` accept header:

```curl
## Request
curl "https://hillexplorer.com/author/hillexplorer/" \
     -H 'Accept: application/activity+json'
```

Have you maybe installed caching plugins?

**Comment by mark4409** [comment]
Yes... do I need to refresh the cache? Does this plugin create additional content that should be excluded from caching? I use a wordpress plugin to create static files, then use varnish to serve them.

**Comment by pfefferle** [comment]
No problem :)

You can try to disable the cache and/or exclude the profile pages from the cache.

**Comment by mark4409** [comment]
Well, that all seemed successful and I've added the contact from both mastodon and friendica. Thanks.

**Comment by pfefferle** [comment]
Nice! have fun 😁
