### ISSUE TITLE
Add field per Post to add AP-handles for mentioning them

### ISSUE THREAD

**Issue by jaschaurbach** [pfefferle/wordpress-activitypub#171]
I would like to mention users in the post but not in the text I am publishing. This is the sam meta-problem a in #165. Depending on where I read the post context might change. There always two audiences I am publishing to: One audience is the AP-consumers, the other audience is folks reading on the website (or via RSS)

I have two use cases for this:

I have a discussion with folks offline (I know, why should ANYONE do this, right?) and in the end I have many thoughts and write a post three days later and this post is For general audience AND those two folks I was ~~drinking~~ talking with. 

The other case ist I am member of something at https://a.gup.pe (a service which creates user on demand and boosts all posts mentioned to that user so everyone who follows that user get it in their timeline. Awesome!

For the template I propose %ccusers% which replaces to //cc: @user1@example.com, @user2@example.com and so on.

As always: Thank for considering :)

**Comment by pfefferle** [comment]
With the latest release it is possible to @-mention users in the way you described: `@user1@example.com`.

There is no nice UI yet, but this is simply because I am not very familar with extending the block-editor. But it is on my list!

**Comment by jaschaurbach** [comment]
Thank you!
