### ISSUE TITLE
I can't found my web in mastodon

### ISSUE THREAD

**Issue by marcoablanco** [pfefferle/wordpress-activitypub#173]
Plugin show me an error in "Salud del sitio" (¿Site Health in english?):
_Your author URL https://www.notodoesprogramacion.es/author/marcoablanco/ does not return valid JSON for application/activity+json. Please check if your hosting supports alternate Accept headers._

But in webfinger, it seems to be ok: https://webfinger.net/lookup/?resource=https%3A%2F%2Fwww.notodoesprogramacion.es%2Fauthor%2Fmarcoablanco%2F

When i search @marcoablanco@www.notodoesprogramacion.es in mastodon.social or xarxa.cloud, my user not appear.

**Comment by pfefferle** [comment]
ActivityPub calls the profile page with the `application/activity+json` header, to get the profile JSON. The WebFinger handle is only an alias for the profile page. If I call your profile page with the header, I get an empty response: 

```
curl "https://www.notodoesprogramacion.es/author/marcoablanco/" \
     -H 'Accept: application/activity+json'
```

Do you perhaps use a caching plugin? It might help to exclude your/the author URL(s).

**Comment by marcoablanco** [comment]
Ok, it's because "Jetpack Boost" plugin. Deactivated and it's works!
