### ISSUE TITLE
Are we ready for a renaissance? Images vs Events = Chaos

### ISSUE THREAD

**Issue by teledyn** [pfefferle/wordpress-activitypub#179]
I'm hoping interest in this plugin picks up in these post-Twitter times ;)

I am using The Event Calendar and just posted my first Event; it goes out to subscribers, but the photos are mangled

See https://mastodon.social/@eso@eighthstreetorchestra.com/109345671915173570 

- It has posted three images, the other two were early editions that I had added but had to replace, seems it sent all three; two of them have been deleted from Media, but the third, [is a valid image (webp) url](https://eighthstreetorchestra.com/wp-content/uploads/2022/11/received_528172889200909.webp)

The WP Event page is https://eighthstreetorchestra.com/event/dance-like-its-1952/

**Comment by mediaformat** [comment]
Duplicate: https://github.com/pfefferle/wordpress-activitypub/issues/149
