### ISSUE TITLE
Option "Hashtags" doesn't work well with special characters

### ISSUE THREAD

**Issue by bocops** [pfefferle/wordpress-activitypub#183]
With the option to "Add hashtags in the content as native tags and replace the #tag with the tag-link." activated, write a blog post containing hashtags with special characters. I tried "#Schlagwörter" and "#Fließtext".

Expected: the complete words should appear as links in the resulting blog post.

Instead, only the prefix up to the special character appears as a link ("#Schlagw", "#Flie"), linking to tags that obviously don't exist.

**Comment by pfefferle** [comment]
Can you share an example?

As far as I know is, that most plattforms does not support umlauts (twitter, mastodon, ...)?!?

**Comment by bocops** [comment]
Sorry, I should have clarified that this bug appears in the Wordpress blog itself after activating the plugin option, not in any resulting posts on other platforms. See image attached.

![image](https://user-images.githubusercontent.com/29770778/202154729-7ca45eee-5673-4620-872e-09ee0ad23100.png)

**Comment by pfefferle** [comment]
I assumed that, I wanted to argue that hashtags does not support Umlauts in general. Maybe that might be the problem that it does not show up on mastodon?

**Comment by bocops** [comment]
The issue described in #182 appears for tags that do not use Umlaute or other special characters. In my various test articles, I used common words such as Hund, Katze, Maus etc., but also random phrases like TestWortEins, TestWortZwei etc. Those tags were not created as hashtags in the content, but separately ("Tags"/"Schlagwörter" functionality of Wordpress).

Here, the issue just exists within a single Wordpress installation and does not extend to any shares of the article. Still, I believe that this plugin causes it by trying to format hashtag-looking strings into links. If this is not possible because the string in question contains special characters, then that specific string should probably not be rewritten at all.

**Comment by pfefferle** [comment]
> Here, the issue just exists within a single Wordpress installation and does not extend to any shares of the article. Still, I believe that this plugin causes it by trying to format hashtag-looking strings into links. If this is not possible because the string in question contains special characters, then that specific string should probably not be rewritten at all.

That is valid point!

**Comment by bocops** [comment]
Having a look at the code, I think it might be enough to just change the regex in [activitypub.php#L22](https://github.com/pfefferle/wordpress-activitypub/blob/7adf5b20aa15f8aa4ce82d2055181d24a4097656/activitypub.php#L22) to only match full words (or nothing at all), like so:

`(?:(?<=\s)|^)#(\w*[A-Za-z_]+\w*$)`

I don't know enough about this repo yet, so I'm not sending a PR for this at the time. Let me know if I should.

**Comment by pfefferle** [comment]
sure, please send a PR! I am not very good at writing regexes, so I'm happy about any help!
