### ISSUE TITLE
Posts are not showing up in other Fediverse sites.

### ISSUE THREAD

**Issue by blueset** [pfefferle/wordpress-activitypub#190]
I recently set up the plugin on my blog, I managed to get the profile to show on other Fediverse sites, but they are not fetching posts from the plugin. I have also checked my outbox API response, which looked normal to me.

---

Tested on: https://blog.1a23.com/
* Author URL: https://blog.1a23.com/author/blueset
* Author handle: `@blueset@blog.1a23.com`
* WebFinger: https://blog.1a23.com/.well-known/webfinger?resource=acct:blueset@blog.1a23.com
* Outbox API endpoint: https://blog.1a23.com/wp-json/activitypub/1.0/users/1/outbox?page=1
* Sample Fediverse fetch outcome (on mastodon.social): https://mastodon.social/@blueset@blog.1a23.com

---

_Originally posted by @blueset in https://github.com/pfefferle/wordpress-activitypub/discussions/185#discussioncomment-4186777_

**Comment by mediaformat** [comment]
Mastodon does not fetch posts when fetching a profile. The exception is `pinned` posts, but we haven't implemented this yet.
Posts can be fetched manually by copying the post url and pasting it into mastodon search.

**Comment by blueset** [comment]
Thanks for the reply! Searching the URL worked for me.
