### ISSUE TITLE
Server not found on Mastodon?

### ISSUE THREAD

**Issue by Flynsarmy** [pfefferle/wordpress-activitypub#197]
I installed the plugin on my site www.flynsarmy.com - the health check is coming back good, the URL https://www.flynsarmy.com/.well-known/webfinger?resource=acct:flynsarmy@www.flynsarmy.com returns correct JSON yet when I go to any mastodon server (for example https://mastodon.gamedev.place/) and search for @flynsarmy@www.flynsarmy.com nothing can be found.

Any idea what's going wrong here?

**Comment by enzocomics** [comment]
Hi there! I checked, and was able to find your profile. Maybe it just needed some time to federate?

![image](https://user-images.githubusercontent.com/4853587/203431849-ede87b2a-7ef1-434e-ae74-6208bfdd9bda.jpeg)

**Comment by Flynsarmy** [comment]
Ahh, I didn't know that's how it worked. New to this platform. Tyvm!

Is there a way to test changes instantly without them needing to federate first?

**Comment by enzocomics** [comment]
You are very welcome! From my experience, when I publish a post on my test site, it appears on Mastodon within a few seconds. I haven’t tested anything like profile updates yet, though.

**Comment by Flynsarmy** [comment]
Any idea why my posts aren't showing up despite it knowing I have 175?
![Uploading Screenshot_20221123-082523.png…]()

**Comment by Flynsarmy** [comment]
Thanks for the responses. You're a legend!

**Comment by enzocomics** [comment]
Thank you too!! 😄 All the best.
