### ISSUE TITLE
Not Found in Wordpress Plugins

### ISSUE THREAD

**Issue by sunjam** [pfefferle/wordpress-activitypub#2]
[Link you posted to the Plugin appstore does not work.](https://wordpress.org/plugins/search/activitypub/)  

Has this been officially released?

**Comment by pfefferle** [comment]
It is not yet released, because it is still work in progress.

**Comment by sunjam** [comment]
Could the issue please remain open until the app is released

**Comment by pfefferle** [comment]
released
