### ISSUE TITLE
Author can be followed and bio is visible but no test posts are federating 

### ISSUE THREAD

**Issue by ryanthomas-org** [pfefferle/wordpress-activitypub#202]
I am curious how to troubleshoot this. I was able to create `@io@mediahex.port0.org` which points to the author of my WordPress install, and I can see the account/profile/avatar from Pleroma. I can also follow it. However, I repeatedly make test posts yet I can never see them from Pleroma. None of the posts seem to be federating, although the bio is. Zero modifications have been made to ngninx, though site health returns no errors. I don't see any PHP fatal errors though I do see a lot of notices about wp-cron, and a number of 404s in the access log looking for paths like `/api/v1/instance/[...]`, `/.well-known/host-meta`, and `status.php` Any guess? This is a managed host, and again I haven't touched nginx yet, but the profile itself is loading and even federated changes made to the bio.

**Comment by enzocomics** [comment]
I'm sorry I can't speak for Pleroma, but I followed you on Mastodon after you posted this and I was able to see your latest post from yesterday.

![image](https://user-images.githubusercontent.com/4853587/204106368-db035be4-684f-4580-9462-e166497efc4d.jpeg)

Are you still having issues with Pleroma?

**Comment by ryanthomas-org** [comment]
Just wanted to say thank you for having tested this on Mastodon for me. I believe this is a limitation of Pleroma or Rebased, but I'm unable to test further at this time
