### ISSUE TITLE
Accounts being given wrong avatar URL

### ISSUE THREAD

**Issue by gausie** [pfefferle/wordpress-activitypub#205]
I noticed that my user displayed the gravatar image rather than my custom avatar uploaded to WP.

Checking WP behaviour I note that

```php
get_avatar(4430); // returns the user's avatar as uploaded to my wordpress instance
get_avatar_url(4430); // returns a url of the user's gravatar
```

Seems like an upstream issue that I couldn't quite diagnose but perhaps we could get a workaround?

**Comment by mediaformat** [comment]
Good to know!

A few other things to note:
Mastodon will not update the avatar until the actor sends a new post, or because of cache until a few days.

Also I've been able to bypass gravatar using [Simple Local Avatars](https://wordpress.org/plugins/simple-local-avatars/)

**Comment by pfefferle** [comment]
What avatar plugin do you use? Maybe you can report that issue so that both methods will return the correct image?

**Comment by gausie** [comment]
I am a fool and forgot that avatars are supplied by a plugin

**Comment by pfefferle** [comment]
@gausie no problem :)

I hope you get it fixed!
