### ISSUE TITLE
Adjust nodeinfo user count

### ISSUE THREAD

**Issue by mediaformat** [pfefferle/wordpress-activitypub#209]
Nodeinfo reports all WP users accounts, even though only those with the role author and above can technically post.
 
`$users = \count_users();`

Original report @heleucht https://pirati.ca/display/ec054ce7-1363-8f94-6546-944144035152

**Comment by pfefferle** [comment]
Makes sense, but it is not true, that commenters are counted, because they will not be added as WordPress users.
