### ISSUE TITLE
Include tags as hashtags in posts

### ISSUE THREAD

**Issue by vanitasvitae** [pfefferle/wordpress-activitypub#21]
It would be nice, if tags would be included in the post as hashtags. I assume this would work best when posting the excerpt of the article.

**Comment by pfefferle** [comment]
I like the idea, but it is not possible using the excerpt, because the excerpt logic does strip all HTML code. Will have to rethink the sharing options a bit.

**Comment by vanitasvitae** [comment]
To be clear, I meant that hashtags would be posted below the excerpt. For example

> This is an awesome blog post about a sleeping cat!
>
> [blog.awesome.net/posts/awesome-cat](blog.awesome.net/posts/awesome-cat)
>
> [#cute](example.com/tags/cute) [#cat](example.com/tags/cat) [#wow](example.com/tags/wow)

**Comment by pfefferle** [comment]
I see!
