### ISSUE TITLE
Critical error when using Friends Plugin and adding new URL to follow

### ISSUE THREAD

**Issue by beckej13820** [pfefferle/wordpress-activitypub#216]
I recently installed the Friends plugin to try to follow other sites from my ActivityPub enabled WordPress.

When adding a URL through the friends interface, this critical error happened on my website. I'm sharing the Error Details and Stacktrace sent to my email.

When seeking help with this issue, you may be asked for some of the following information:
WordPress version 6.1.1
Active theme: Astra (version 3.9.4)
Current plugin: ActivityPub (version 0.14.1)
PHP version 8.0.25

Error Details
=============
An error of type E_ERROR was caused in line 114 of the file /home/edbecksu/ed-beck.com/wp-content/plugins/activitypub/includes/functions.php. Error message: Uncaught Error: Class "Acivitypub\Webfinger" not found in /home/edbecksu/ed-beck.com/wp-content/plugins/activitypub/includes/functions.php:114
Stack trace:
#0 /home/edbecksu/ed-beck.com/wp-content/plugins/activitypub/integration/class-friends-feed-parser-activitypub.php(70): Activitypub\get_remote_metadata_by_actor('https://toot.si/...')
#1 /home/edbecksu/ed-beck.com/wp-content/plugins/friends/includes/class-feed.php(881): Activitypub\Friends_Feed_Parser_ActivityPub->update_feed_details(Array)
#2 /home/edbecksu/ed-beck.com/wp-content/plugins/friends/includes/class-admin.php(1570): Friends\Feed->discover_available_feeds('https://toot.si/...')
#3 /home/edbecksu/ed-beck.com/wp-content/plugins/friends/includes/class-admin.php(1771): Friends\Admin->process_admin_add_friend(Array)
#4 /home/edbecksu/ed-beck.com/wp-includes/class-wp-hook.php(308): Friends\Admin->render_admin_add_friend('')
#5 /home/edbecksu/ed-beck.com/wp-includes/class-wp-hook.php(332): WP_Hook->apply_filters('', Array)
#6 /home/edbecksu/ed-beck.com/wp-includes/plugin.php(517): WP_Hook->do_action(Array)
#7 /home/edbecksu/ed-beck.com/wp-admin/admin.php(259): do_action('friends_page_ad...')
#8 {main}
  thrown

**Comment by pfefferle** [comment]
@akirk can you help here?

**Comment by akirk** [comment]
Oh no, looks like a typo:`Acivitypub`. Fixed in #217.

**Comment by akirk** [comment]
As a workaround for the Friends Plugin you can also use the URL, like for `@abc@mastodon.social` the URL would typically be `https://mastodon.social/users/abc`.
