### ISSUE TITLE
Excerpt uses 400 words instead of 400 characters

### ISSUE THREAD

**Issue by TiiaAurora** [pfefferle/wordpress-activitypub#218]
I published my first blog post with the plugin active and the post itself was a 400 word wall of text (instead of 400 character excerpt) in the actual Fedi post. 

Images showing the bug: 

![image](https://user-images.githubusercontent.com/6146434/206899049-580206d5-13e1-48c9-b70e-8d27cef3dc66.png)
![image](https://user-images.githubusercontent.com/6146434/206899029-eabc9e9b-5314-46df-8cd2-b157b9390498.png)

**Comment by lapineige** [comment]
Actually I would see that as an interesting option : we could choose either to publish a certain length of text in characters (so it's always the same space taken), or to publish a certain amount of words to give a more or less accurate introduction to the blog post.

Would that be possible ?

**Comment by pfefferle** [comment]
Sure, I think so!

**Comment by pfefferle** [comment]
I had the idea to use shortcodes instead of `%excerpt%` to be able to use params like `[ap_excerpt count_type="words" count="400"]`. But how do I pass the `post_ID` to the shortcode? Any ideas @akirk @mediaformat ?

**Comment by akirk** [comment]
We should be using the `setup_postdata()` function so that in the shortcode `get_the_ID()` can be called.

**Comment by pfefferle** [comment]
can you send me a link to the "Gutenberg template blocks" documentation?

**Comment by belaset** [comment]
If you're using the classic editor, IIRC you can set the excerpt cutoff with the  tag. (I don't know if that's still how it's done with the new editor though, sorry)

**Comment by ifringe** [comment]
Chiming in: While you are pondering this, in addition to breaking on words or characters, it would be also be useful to break on the first paragraph.

This lets me write an intro to my blog post, which may be longer or shorter than X words/characters, which is then posted. In practice, the intro paragraph should be short to prevent the wall of text, but I would be assured of getting the whole paragraph.

**Comment by belaset** [comment]
I tried setting the excerpt cutoff with the 'more' tag (it seems to have been stripped out of my previous comment, because I forgot to escape it and of course it was) but the cut didn't, well, make the cut. And neither did any of my paragraph breaks. (Is that because I'm using the classic editor? I don't have to put in 'p' tags for paragraph breaks to show up on the blog itself, so I didn't know they wouldn't come across to Mastodon.

**Comment by pfefferle** [comment]
I think it should work if you set the excerpt by hand to exactly what you want to see on mastodon, as a quick hack!?!

**Comment by jaschaurbach** [comment]
Can confirm, this works.

**Comment by thomasjwebb** [comment]
Ah thanks for that tip. I'd prefer it to respect the more tag (and not strip returns as it currently does) but manually specifying the excerpt is good enough for now. I wish I found this page earlier.

**Comment by pfefferle** [comment]
Fixed with: https://github.com/pfefferle/wordpress-activitypub/pull/247

Thanks @toolstack
