### ISSUE TITLE
Can't add from some servers

### ISSUE THREAD

**Issue by mrrcollins** [pfefferle/wordpress-activitypub#219]
I was able to add users from mastodon.world and scholar.social without issue, but when I try to add a user from mastodon.cloud or hcommons.social I get an error:

`There has been a critical error on this website. Please check your site admin email inbox for instructions.

[Learn more about troubleshooting WordPress.](https://wordpress.org/support/article/faq-troubleshooting/)`

The error from the email is:

`When seeking help with this issue, you may be asked for some of the following information:
WordPress version 6.1.1
Active theme: Rare Child (version 1.0.0)
Current plugin: ActivityPub (version 0.14.2)
PHP version 7.4.33

Error Details
=============
An error of type E_ERROR was caused in line 121 of the file FOLDER/wp-content/plugins/activitypub/includes/functions.php. Error message: Uncaught Error: Object of class WP_Error could not be converted to string in FOLDER/wp-content/plugins/activitypub/includes/functions.php:121
Stack trace:
#0 FOLDER/wp-content/plugins/activitypub/integration/class-friends-feed-parser-activitypub.php(70): Activitypub\get_remote_metadata_by_actor()
#1 FOLDER/wp-content/plugins/friends/includes/class-feed.php(881): Activitypub\Friends_Feed_Parser_ActivityPub->update_feed_details()
#2 FOLDER/wp-content/plugins/friends/includes/class-admin.php(1579): Friends\Feed->discover_available_feeds()
#3 FOLDER/wp-content/plugins/friends/includes/class-admin.php(1780): Friends\Admin->process_admin_add_friend()
#4 FOLDER/wp-includes/class-wp-hook.php(308): Friends\Admin->render_admin_add_friend()
#5 FOLDER/wp-includes/class-wp-hook.php(332): WP_Hook->apply_filters()
#6 FOLDER/wp-includes/plugin.php(517): WP_Hook->do_action()
#7 FOLDER/wp-admin/admin.php(259): do_action()
#8 {mai
`

I don't know if the issue is with my setup or the servers I'm trying to connect to. 😎

**Comment by pfefferle** [comment]
Hmm, the plugin should not fail with a PHP fatal error ever. I will have a look, thanks for reporting.

**Comment by pfefferle** [comment]
@akirk is this problem also fixed with the latest version of the friends plugin?

**Comment by akirk** [comment]
It's actually a bug in the ActivityPub plugin and will be fixed with #213 which adds a [`if ( is_wp_error( $actor ) ) {`](https://github.com/pfefferle/wordpress-activitypub/pull/213/files#diff-1c08b27bcf43583c75cbc442bc401638be3427586fe544f3389e22c9979fa1afR120).

**Comment by pfefferle** [comment]
oh! can you file a PR only for that change, so that we mabe can release a quick minor?

**Comment by akirk** [comment]
Ok, I created https://github.com/pfefferle/wordpress-activitypub/pull/220 with the fix.
