### ISSUE TITLE
Unable to follow from Mastodon

### ISSUE THREAD

**Issue by 5teveroy** [pfefferle/wordpress-activitypub#22]
When I search for my user@domain from Mastodon, nothing is found. When I look at https://client.webfinger.net/lookup?resource=steve%40micro.steveroy.ca, I see that  it's not broadcasting the /author/steve URL as it should be but I'm not sure how to rectify that.

I don't think I have any plugin installed that rewrites or changes that info but here is the list of active plugins:

- ActivityPub
- Akismet
- Classic Editor
- JSON Feed
- Mastodon Auto Share

Anything else I should be looking at?

**Comment by pfefferle** [comment]
Hey @5teveroy thanks for switching to GitHub issues :)

I think it is your theme... Can you go to the `customizer` -> `General Options` and then enable `Enable Multi-Author Mode... Then it should work...

**Comment by 5teveroy** [comment]
You're right, it works, just like magic! Thanks!

**Comment by pfefferle** [comment]
😁
