### ISSUE TITLE
Convert tag slugs to CamelCase hashtags

### ISSUE THREAD

**Issue by kristianserrano** [pfefferle/wordpress-activitypub#222]
Is it possible for tags to be converted from slugs to #CamelCase hashtags? For example, if I write a tag as `Web Design`, its slug will be `web-design`. I think it would be ideal if this were to be converted to `#WebDesign`.

**Comment by timnolte** [comment]
This is sort of related to https://github.com/pfefferle/wordpress-activitypub/issues/204 which looks like it should be getting fixed. It seems like it would be recommended for widespread compatibility to just use a real single "word" tag instead of using spaces.
