### ISSUE TITLE
Activitypub comments link to an avatar on third third party domain - GDPR issue

### ISSUE THREAD

**Issue by jaschaurbach** [pfefferle/wordpress-activitypub#227]
Thies is an obvious thing: A comment via activitypub contain a link to the avatar hosted on the server from where the comment was made, e.g `https://files.mastodon.social/accounts/avatars/000/063/916/original/10a5ff83f9ea14a0.png`

While it is totally fine to have an avatar shown from a third party site in the comment it is a GDPR issue. I need to inform the users that they will load sources from a third party and I need to list this third party in my privacy policy. This is of course not easy to handle. 

I suggest to enable a function that allows me to mirror the avatars locally with following constraints:
If the last comment of this account gets deleted in WordPress, the avatar gets deleted as well.
check every $timframe for a new avatar. If not, keep the old. If yes, mirror the new one, delete the old.
If the instance is not reachable for more than $timeframe (e.g. six weeks) or the user is not available for $timeframe (e.g. six weeks) delete the avatar and delete the URL to the profile, keep the comment.

**Comment by jaschaurbach** [comment]
Disregard. The plugin „Avatar Privacy“ does most of the job

**Comment by pfefferle** [comment]
But this is a good point, maybe I add this plugin to the list of recommended plugins!
