### ISSUE TITLE
Publishing a one-page update

### ISSUE THREAD

**Issue by juliojulian** [pfefferle/wordpress-activitypub#23]
I changed an image on a fixed page of my WP (which is already several years old) and received in mastodon as if it were the publication of an entry. 
Is it possible to avoid this in some way? or maybe in the future?
(Automatic translation from Spanish, sorry)

**Comment by vanitasvitae** [comment]
I second this. It'd be nice to have a setting to avoid publishing updates, as well as a setting to avoid publishing pages in general.

Maybe as an option in wordpress' publication sidebar?
