### ISSUE TITLE
WooCommerce Customer Data Exposed

### ISSUE THREAD

**Issue by d3cline** [pfefferle/wordpress-activitypub#230]
If you have a WooCommerce installation every customer's user data is searchable and exposed. This has to have a fix where only a given user class is automatically populated or exposed in any way.

Also any customer who buys a product is now able to post as my instance.

This is a serious breach of data security and should be a high priority. Under no circumstance should customer data be leaked this way or be possibly abused in this way.

WooCommerce is a very popular plugin, without any warnings anyone installing nodeinfo plugin is now back dooring their customer database. And giving any attacker the ability to speak as the company.

To reproduce simply install WooCommerce, and set up some customer accounts. Those accounts can now be found by federation search.

The safe default must be admin or editor level or higher only. "normal customer accounts" users or "subscription" users can not be searchable or in ActivityPub whatsoever. Custom plugins which allow "wholesale" accounts must also be included.

**Comment by d3cline** [comment]
![image](https://user-images.githubusercontent.com/77483/209577637-bacd3da9-d593-41cb-b3af-92a3daa212df.png)

Ed is one of my customers,  He should not be showing up under any circumstance. If ed was a bad actor he could via some API calls start posting to the feddy as someone who represents my company. 

This is the security issue. It must be fixed or woocommerce can't use this plugin.

**Comment by pfefferle** [comment]
He could not post anything, because the plugin does not add the right to post and there is no index, anyone could crawl, so you have to guess usernames, to find them. But I agree, that woocommerce users has to be excluded from the plugin!

**Comment by d3cline** [comment]
Thanks for taking a look. I would do the PR but you don't want my PHP lol. I will promote the plugin and help people in our hosting platform and on the feddy use this once I know its secure with woocommerce. Thanks again!

**Comment by pfefferle** [comment]
Thanks for reporting! I will release a security and privacy fixing update asap!
