### ISSUE TITLE
Post-Image als Bild einfügen?

### ISSUE THREAD

**Issue by herrMartin** [pfefferle/wordpress-activitypub#232]
wäre es möglich das post-image auch irgendwie als template tag zu bekommen

**Comment by pfefferle** [comment]
Das Bild sollte eigentlich immer automatisch angehängt werden!

**Comment by jaschaurbach** [comment]
So weit das Verhalten zumindest bei meiner Installation :)

**Comment by pfefferle** [comment]
Du kannst das Bild jetzt auch über `[ap_image]` in den Post-Content einfügen.
