### ISSUE TITLE
How do I do mentions from my blog?

### ISSUE THREAD

**Issue by db0** [pfefferle/wordpress-activitypub#234]
I tried to mention a user here: https://dbzer0.com/blog/i-wonder-what-happens-when-i-do-this/ but it doesn't seem to link the profile or initiate a mention. How do I do this?

**Comment by akirk** [comment]
This is being implemented in #213.

**Comment by pfefferle** [comment]
This does now work with the latest version, simply use `@username@domain.tld`!
