### ISSUE TITLE
Site plugin not working for non-site-administrator users?

### ISSUE THREAD

**Issue by alecmuffett** [pfefferle/wordpress-activitypub#238]
I have installed:

* ActivityPub
* Friends
* NodeInfo
* WebFInger

...and Webfinger is working (https://alecmuffett.com/.well-known/webfinger?resource=acct:alecm@alecmuffett.com) so I presume that I am publishing okay, however I have (at least two) issues:

1. When I am logged into my blog as my usual "Editor" role, the `/friends/` page shows the placeholder page ("Enter your blog URL to join my network") rather than a feed.
2. When I am logged into my blog as "Administrator" — which I generally do not do, because of security — the `/friends/` page shows a "Main Feed" but no content from subscriptions yet ("Unfortunately, we could not find a post") even though the people I subscribe to have updated.

I am not sure where to start with debugging this. I am not even sure that the plugin is meant to work for anyone other than the site administrator.

**Comment by pfefferle** [comment]
@akirk can you help here?

**Comment by akirk** [comment]
Yes, this is related to the Friends plugin, let's move the discussion to https://github.com/akirk/friends/issues/120. Right now an Administrator account is required because following other users implies the creation of new users which is something an Editor role cannot do.
