### ISSUE TITLE
Template Pattern: Featured Image

### ISSUE THREAD

**Issue by nerdteacher** [pfefferle/wordpress-activitypub#243]
Apologies if I missed it! I tried searching and didn't see it, so I might have searched for the wrong terms. But it'd be nice if the template patterns also included featured image somehow?

(Thanks! 💕)

**Comment by pfefferle** [comment]
the featured image is set as attachment, mastodon does not yet support inline images, as far as I know.

**Comment by mikewmerritt** [comment]
When I first federated my blog with the plugin, Mastodon posted both the full content and the inline image! But now I can't replicate that behavior.

**Comment by pfefferle** [comment]
Hmmm, I will check! Thanks for the info @mikewmerritt !

**Comment by pfefferle** [comment]
@mikewmerritt I found the place in the Mastodon API: https://docs.joinmastodon.org/spec/activitypub/#sanitization

All `<img>` tags would be striped, so even if there is a pattern for the featured image, it would not be displayed inline I think.

**Comment by pfefferle** [comment]
this is now available with the shortcode `[ap_image]`
