### ISSUE TITLE
Inconsistencies in terms of what actually shows up in Mastodon

### ISSUE THREAD

**Issue by thomasjwebb** [pfefferle/wordpress-activitypub#252]
I cannot reliably get ActivityPub to show the excerpt, the tags and the link or shortlink. Sometimes the tags are missing outright, sometimes the link shows immediately after the tags with no enter despite that being there in the template. 

Here is a [test post](https://thomaswebb.net/2023/01/15/activitypub-test-post/) that I made and I included a screenshot of what it looks like on mastodon (mostly right except the tags are missing). I also included a screenshot of the end of another post showing that the tags are there, but no enter before the shortlink. I also included a screenshot of my settings.

![Screenshot_20230115_091528](https://user-images.githubusercontent.com/16326686/212556431-919c28af-20b8-4e64-9d5b-c60e35e427c8.png)
![Screenshot_20230115_091322](https://user-images.githubusercontent.com/16326686/212556432-f3be09a8-4a35-4ea5-9ff4-7ccd3d54f80d.png)
![Screenshot_20230115_091253](https://user-images.githubusercontent.com/16326686/212556433-082731e4-efba-41d4-ba44-55a52c9b8940.png)

**Comment by bocops** [comment]
This also seems to be my issue in #182. I've added a workaround there that was shared with me. Check if that helps you as well.

**Comment by thomasjwebb** [comment]
Ah okay, thanks! So my two go-to workarounds are gonna be manually specifying the excerpt and scheduling posts. Seems reasonable enough. I'll mark this as a duplicate since I didn't realize the other issue was about the same thing.
