### ISSUE TITLE
Not all user accounts are found

### ISSUE THREAD

**Issue by wilenius** [pfefferle/wordpress-activitypub#254]
Hi, we are using the latest plugin version and the latest Wordpress version.

For some reason, some of our users are missing from ActivityPub/Webfinger side of things. I tried asking one problematic account user to login in and reset password, also tried changing user roles. Neither helped. It's not a cache or a plugin conflict thing either. Any ideas?

Webfinger returns a 404:

`{"code":"activitypub_user_not_found","message":"User not found","data":{"status":404}}
`

Most of our users have never logged in – might that be the issue? However, we tested one of these profiles by resetting the password, and logging in. The user sees the ActivityPub profile URL in their settings, but when I, as admin, look at the profile, I don't see the ActivityPub settings in the profile.

**Comment by pfefferle** [comment]
ActivityPub only shows Users that can `publish_posts`, because it does not make sense for any other user. If they all can `publish_posts` it would be helpfull if you could share an WebFinger Identifier that does not work, so I can have a look!

**Comment by wilenius** [comment]
Thanks for the reply. I thought that we tried changing roles yesterday, but tried again, and indeed, when I change the role from contributor to editor, everything works. However, we have a site with about 300 authors, and most of them have a contributor role – we process the texts outside Wordpress, and our editors publish the texts, not the authors – that's why they have a contributor role. But I do see the logic here. 

Perhaps the best course of action is to disable the plugin for now, and wait for the possibility of #1 being resolved? Or what do you think?
