### ISSUE TITLE
Customizable excerpt/toot length

### ISSUE THREAD

**Issue by adegans** [pfefferle/wordpress-activitypub#258]
It defaults to 400. Which is usually fine.
But a custom excerpt offers a bit more options to get people to visit the site.

So to add a setting to set any number between, say 50-400 would be nice.
For my own purposes I think 200 would be nice.

Or a bit more advanced: Have the plugin count and share words. Share 20 words with a maximum of 400 chars or something. Or the first 2 sentences (stop after the 2nd . (period))

All this helps with formatting the posts on Mastodon etc. And lets users create better intro's for the post to be shared.

Currently it looks like this: https://home.social/@arnandegans@ajdg.solutions/109700791992314506
Which is a bit messy.

**Comment by adegans** [comment]
Another option is to look at SEO plugins and use the snippet from that... But with the various plugins and different ways they store data... Maybe that's not so good. But just a thought.

**Comment by pfefferle** [comment]
This will be part of this PR: https://github.com/pfefferle/wordpress-activitypub/pull/250

**Comment by pfefferle** [comment]
This is now possible with `[ap_excerpt length="200"]`
