### ISSUE TITLE
Support for Post Kinds (aka map post types to activity verbs)

### ISSUE THREAD

**Issue by xavierroy** [pfefferle/wordpress-activitypub#26]
It would be nice if we could map the post types with the corresponding activity verbs especially when I have the Post Kinds plugin installed.

Say, I read a book and use the read post type, it would be nice if the AS shows me as [reading](https://www.w3.org/TR/activitystreams-vocabulary/#dfn-read) the book. And there are several other post types that could be mapped to the other AS activity verbs.

(Originally published at: https://xavierroy.com/b/21h)

**Comment by Cambridgeport90** [comment]
Definitely. My site, for instance, makes heavy use of post kinds.
