### ISSUE TITLE
After v0.16 update, posts appear blank on Mastodon

### ISSUE THREAD

**Issue by novakeith** [pfefferle/wordpress-activitypub#266]
<img width="574" alt="Screenshot 2023-02-01 at 8 51 04 PM" src="https://user-images.githubusercontent.com/11334820/216227644-6dd51dd9-11df-4dce-97ea-d43827fbe383.png">

My wordpress blog is set to automatically update plugins. I tried publishing a test post tonight and unfortunately, its coming up blank when viewed on a Mastodon instance (Mas.To); oddly enough, if I repost it and view it on my Akkoma instance, it shows up fully. (Sidebar - I seem to have trouble following my WP blog directly from Akkoma - my account is stuck at "Request Pending").

**Comment by novakeith** [comment]
I believe this describes the same issue - https://wordpress.org/support/topic/shortcodes-empty-when-post-published/

**Comment by jeherve** [comment]
I ran into that just now as well, thanks for the quick fix!
