### ISSUE TITLE
Support selective publishing

### ISSUE THREAD

**Issue by xavierroy** [pfefferle/wordpress-activitypub#27]
Is it possible to build in filters so that I can withhold publishing a certain category or tags? Say I have a food log and I would not want to tell the Fediverse what I had for breakfast or lunch. 🙂 I am thinking of a filter (could be a category/tag/post kind/post format). Anything that matches the filter does not go through to the fediverse.

(Originally published at: https://xavierroy.com/b/21k)

**Comment by asgartech** [comment]
On a related note, wordpress-activitypub probably shouldn't publish pages to the Fediverse. Just posts.

**Comment by lapineige** [comment]
It would be even better to have such an option for each article.
Some articles are not meant to be shared to the fediverse (for instance test articles, that are removed later, are spamming in some way).
