### ISSUE TITLE
ActivityPub doesn't play well with W3 Total Cache plugin

### ISSUE THREAD

**Issue by imrehg** [pfefferle/wordpress-activitypub#275]
[W3 Total Cache](https://wordpress.org/plugins/w3-total-cache/) (W3TC) is very widely used caching plugin. ActivityPub overrides the data returned on the author pages for a specific header (`Accept: application/activity+json`), but W3TC doesn't know anything about it, and as soon as there's a regular request to the authors page, it caches the page as `html`, breaking the above JSON entry. This shows up in the Site Health report as a critical issue as well ("Author URL is not accessible").

This interaction between the two plugins can be worked around if I specifically disable caching of author pages in W3TC by going to `Performance` > `Page Cache` > `Advanced` > `Never cache the following pages`, and add a value for `/authors/.+`.

Instead of doing this manually, it could work automatically, as this plugin could potentially signal to W3TC to disable caching on the relevant author pages, following [this FAQ item](https://github.com/BoldGrid/w3-total-cache/wiki/FAQ%3A-Developers#how-can-i-prevent-caching-directly-in-my-templates-etc). I haven't tried it, but had this suggestion from multiple people.

**Comment by imrehg** [comment]
Actually trying it a bit more, it's not just the author pages, but all pages that are rendered in `application/activity+json` format (author, post, blog).

**Comment by pfefferle** [comment]
And that is the problem why I not yet have implemented filters for the big caching plugins. I would prefer to file an issue to support content negotiations and to ignore Accept headers other than html.

**Comment by imrehg** [comment]
I've been digging further in the meantime, and totally agree with the above (and the caching plugins' behaviours seems to be even more subtle chaos / buggy than I've thought).

I'll take this over to the other side indeed.
Cheers!
