### ISSUE TITLE
Option to set "published" to date of first blog post instead of date of connection to the Fediverse

### ISSUE THREAD

**Issue by stevenjaycohen** [pfefferle/wordpress-activitypub#276]
`"published": "1995-01-16T10:01:00Z",`

Yep, that is the date of my first blog post (long before cafeLog, b2evo, and Wordpress).

[https://stevenjaycohen.com/1995/01/16/what-i-ask/](url)

I would like the option to set ActivityPub to the date of the first blog post. It does pick up the total number of blog posts, but to truly represent that correctly, it should have the option to correctly identify the span of time within which those posts occured.

Arguably it is more factually accurate to say that this instance has existed since 1995 than it is to say that 28 years of content has been created since connecting the site to the Fediverse.

I am not asking that this be a default, but a switch within the plugin. I can see the logic for the current behavior as well. I am just making the argument for historical accuracy :)

**Comment by pfefferle** [comment]
I am not sure I understand your request. The plugin uses the date, where a post is published, you can see that by adding `/activitypub` to the end of a post-url: https://stevenjaycohen.com/1995/01/16/what-i-ask/activitypub/

**Comment by pfefferle** [comment]
Ah, I see! You are referring to the publish attribute of a profile, that is currently missing completely in the plugin. Good point!

**Comment by stevenjaycohen** [comment]
> Ah, I see! You are referring to the publish attribute of a profile, that is currently missing completely in the plugin. Good point!

Exactly! 

**(the following is not really a digression, I promise)**
Originally, I was one of the people who used the manual webfinger file hack to get the plugin working. In trying to figure out why I needed that hack, I eventually came across the Mastodon Server in 6 files post:

[https://justingarrison.com/blog/2022-12-06-mastodon-files-instance/](url)

So, I started playing with the webfinger file and then trying the other files that he mentions. Eventually, I realized that the other files were all being superseded by the plugin. But, before heading back to try and figure out if I could remove the hack and keep it all working, **I did note the things he sets both in the webfinger and the user file.** That is when I started to wonder how these things could be best implemented in the plugin.

To finish the story, by adding your webfinger plugin and removing the hack file, I got basic functionality. So, I added your nodeinfo plugin as well and saw the json expand even more. This is when i started to wonder if I could write some functions to set some values within the plugin, and if I got any interesting functionality working, I would then submit those functions to you for either the community to use as is or to be formally implemented within the plugin.

**Comment by stevenjaycohen** [comment]
I do wonder if it might be simpler to have a toggle for single vs multi-user wordpress blogs since what might be considered a profile page, a web page, and a blog might be simpler to deploy and refine for single user systems first. It would be interesting to know what percentage of the plugin's users are the sole users of their blog.
