### ISSUE TITLE
Make username (webfinger) customizable

### ISSUE THREAD

**Issue by merinleona** [pfefferle/wordpress-activitypub#28]
I am not a fan of the fact that this used my loginname for wordpress as the user handle. I very much prefer Pterotypes approach to just use blog@. Now i deinstalled the plugin again, but i donÄt know how to delete the Account created on the Fediverse since I don't have access to it. How do I do that?
Thank you

**Comment by pfefferle** [comment]
I have chosen the username, because this supports multiple users per blog. What are your concerns using the username?

You have no account in the „fediverse“ it all works decentral. If you reinstall the plugin, your account is gone.

**Comment by pfefferle** [comment]
And, as far as I know pterotype also works this way...

**Comment by merinleona** [comment]
i deleted both plugins. The Account created by pterotype (blog@my-domain) can't be find anymore. But the one created by Activitypub still shows up when I search for my domain on Mastadon. So it has to been entered into some registry or some part of the plugin does not deacitvate when you deinstall.

**Comment by pfefferle** [comment]
Ah, I see... This is a problem with mastodons caching system... 😞

**Comment by pfefferle** [comment]
Or it is, because pterotype also uses the username...

**Comment by merinleona** [comment]
So it will disappear after a bit? I thought it had something to do with the plugin since I deinstalled both at the same time and the pterotype account vanished instantly.

**Comment by merinleona** [comment]
I deinstalled pterotype as well

**Comment by pfefferle** [comment]
You can try it on webfinger.net

If you provide me your blog URL, I will have a look.

**Comment by merinleona** [comment]
I would not mind if it was my Display name btw. But I don't like it being my Admin login name.. it looks stupid^^ ( not your problem me picking a stupid name and being vane^^)

**Comment by merinleona** [comment]
It's snowshaven.space

**Comment by pfefferle** [comment]
Everything is deleted properly, at least as far as I can see (no more visible API endpoints). So it really seems a caching issue.

**Comment by Suitbert** [comment]
I would like an input field, where I would enter a name of my choice. Don't like it, to be forced to use WP username. Would that be possible?

**Comment by merinleona** [comment]
Thank you for your time :)

**Comment by pfefferle** [comment]
@Suitbert because of any security reasons and/or other concerns or simply because of a "stupid" login name?

In the second case the easiest solution would be to change the login name: https://www.wpbeginner.com/wp-tutorials/how-to-change-your-wordpress-username/

**Comment by pfefferle** [comment]
@Suitbert but to answer you question: Sure it is possible.

**Comment by Suitbert** [comment]
Yes, would prefer not to use the WP username, because I do use different names for admin, editor etc. I do not want to show the names in public.

**Comment by mediaformat** [comment]
@Suitbert could it be based on pseudonym field?

**Comment by Cambridgeport90** [comment]
I definitely like this approach; needs to support multiple authors. that's still an interesting spot. Only thing that would be even cooler, is if for instance, your site has a "site" account, say, on an instance you run, the plugin should allow you to pick the instance that it uses, if possible, rather than creating another account on the fediverrse. I'm having issues getting people to follow my blog, even though they follow my normal account and interact with it. So, there also needs to be a betterr form of discovery.

**Comment by tiotrom** [comment]
> In the second case the easiest solution would be to change the login name: https://www.wpbeginner.com/wp-tutorials/how-to-change-your-wordpress-username/

I did so after I already had the plugin active and all that. And it doesn't find my new username in Mastodon. Finds it in Friendica but even tho I click follow, it cannot follow.

Original handle: @tiotrom@www.tiotrom.com
New one: @tio@www.tiotrom.com
