### ISSUE TITLE
Replies from GoToSocial and Takahe not showing up

### ISSUE THREAD

**Issue by kvibber** [pfefferle/wordpress-activitypub#281]
When GTS hits the inbox, the plugin is throwing a 500 error.

When Takahe hits the inbox, the plugin responds with a 202 result.

Neither set of replies makes it into the comments list on WP, not even the spam folder.

I have a test GTS instance I can try to get more debugging info from, and I'll see what else I can get on the WordPress side too.

**Comment by pfefferle** [comment]
Have you also checked the trash folder? I don't know why but sometimes comments end up there 😞

**Comment by pfefferle** [comment]
Can you explain to me what GTS is? Never heard of it before!

**Comment by lapineige** [comment]
An ActivityPub-based microblogging server (only, no front-end): https://gotosocial.org/ https://github.com/superseriousbusiness/gotosocial

**Comment by pfefferle** [comment]
I see, thanks for the info! Let me know if you find something!

Have you checked the trash for comments?

**Comment by kvibber** [comment]
No sign of the comments in trash, spam or pending.

I turned on WordPress debugging long enough to collect a stacktrace (several, since it retries) from GoToSocial's attempt to send a reply. 

The reply can be seen here on my GoToSocial test server, along with the original post on my blog:
https://gts.keysmash.xyz/@kelsonv/statuses/01GSAX5XAA64Q27X5KJMP8FNPQ

[gts-reply-to-wp-error.txt](https://github.com/pfefferle/wordpress-activitypub/files/10745104/gts-reply-to-wp-error.txt)

It looks like there's something the plugin is expecting to be an array that's just one string in the JSON that GTS sends, possibly the @context judging by 'https://www.w3....'. When I have time later I should be able to dig up a sample of the JSON.

**Comment by pfefferle** [comment]
Ping!

**Comment by lapineige** [comment]
I mean, test from a GTS server, but not another Wordpress+ActivityPub server.

**Comment by kvibber** [comment]
Here's the JSON from my GoToSocial debug log for a new reply to a WordPress blog post:

[gts-create-reply.txt](https://github.com/pfefferle/wordpress-activitypub/files/10752395/gts-create-reply.txt)

This one can be seen here:
https://gts.keysmash.xyz/@kelsonv/statuses/01GSC9S6DND8YMJ1FGKXBJ40PF

(don't mind the duplicated image on the copy of the blog post, that's a bug on GTS's end that seems to be fixed in the latest build judging by more recent posts)

**Comment by pfefferle** [comment]
I found the issue, thanks a lot for your work @kvibber and the debug data!
