### ISSUE TITLE
Webfinger lookup gives HTTP 400 with 'missing "resource" parameter'

### ISSUE THREAD

**Issue by joshhansen** [pfefferle/wordpress-activitypub#287]
I've installed the ActivityPub plugin on my blog at https://joshhansen.net, but when I test it using webfinger.net it returns a 400 error.

When I run a GET request to the same url ( https://joshhansen.net/.well-known/webfinger?resource=acct%3Ajosh%40joshhansen.net ) using curl, it gives:

```
missing "resource" parameter
```
which is particularly strange since `resource` is clearly specified.

The "Site Health" report also has this message:

> 
> WebFinger endpoint is not accessible ActivityPub
> 
> Your WebFinger endpoint https://joshhansen.net/.well-known/webfinger?resource=acct:josh@joshhansen.net does not return valid JSON for application/jrd+json.

I'm using Nginx with PHP-FPM.

As my blog runs in the root directory, I don't think this is a matter of URL redirects being needed.

Would be happy to provide any needed logs or help with diagnosing the issue.

**Comment by pfefferle** [comment]
I am not sure what you have done in the meantime, but WebFinger seems to work properly now: https://webfinger.net/lookup/?resource=josh%40joshhansen.net

**Comment by joshhansen** [comment]
Yes, I added this:
```
    location ~* /.well-known {
        try_files $uri $uri/ /index.php?$args;
    }
```
Apologies for not closing this sooner, thanks for your time
