### ISSUE TITLE
error 0.4.0 follower list

### ISSUE THREAD

**Issue by Suitbert** [pfefferle/wordpress-activitypub#29]
hello,
after updating plugin 0.3.2 to 0.4.0 the follower list does show the following error messages.
regards,
Suitbert

----------------

Warning: count(): Parameter must be an array or an object that implements Countable in /www/htdocs/w00bd103/monz.photos5/wp-content/plugins/activitypub/includes/class-db-activitypub-followers.php on line 12

Warning: count(): Parameter must be an array or an object that implements Countable in /www/htdocs/w00bd103/monz.photos5/wp-content/plugins/activitypub/includes/class-db-activitypub-followers.php on line 12

Warning: count(): Parameter must be an array or an object that implements Countable in /www/htdocs/w00bd103/monz.photos5/wp-content/plugins/activitypub/includes/class-db-activitypub-followers.php on line 12

Warning: count(): Parameter must be an array or an object that implements Countable in /www/htdocs/w00bd103/monz.photos5/wp-content/plugins/activitypub/includes/class-db-activitypub-followers.php on line 12
https://social.tchncs.de/users/suitbertmonz
https://mastodon.social/users/pfefferle
https://libranet.de/profile/suitbertmonz

**Comment by pfefferle** [comment]
mist! sorry, I try to fix it asap!

**Comment by pfefferle** [comment]
should be fixed in v0.4.1
