### ISSUE TITLE
Cut off www part

### ISSUE THREAD

**Issue by nichu42** [pfefferle/wordpress-activitypub#290]
Hey there,

I have published my wordpress blog under www.blog.ext
After installing the ActivityPub plug-in, users are reachable through @user@www.blog.ext, which both looks kind of ugly and isn't really what Fediverse handles look like.
Would it be possible to cut off the www. part, while keeping the blog at the current URL (I wouldn't want to change it due to SEO).

I have searched through other issues but couldn't find anything about this, even though I can hardly believe I am the only one with this request. Maybe I'm missing something basic? If so, I'd appreciate if you could point me in the right direction.

**Comment by zlugg** [comment]
The "www." part is technically a subdomain. It would only be possible if www.domain.com is the same as domain.com on the server. If they are the same and you don't have a redirect from domain.com to www.domain.com then users should be reachable through @user@domain.com .

**Comment by zlugg** [comment]
My opinion is at "www" should not be used if not necessary. Why not move it and do a 301 redirect. https://www.semrush.com/blog/301-redirects/

**Comment by nichu42** [comment]
@pfefferle: Thank you for your kind response. I understand that you cannot simply strip any 3rd level domain. But do you think it could be possible to have this as an option?
I'd like to have my company join the Fediverse and your plug-in seems to be an elegant an easy way to achieve this. It's only that name@www.company.com looks ugly... and not really Fediverse-like.

**Comment by pfefferle** [comment]
@zlugg a redirect is never bad, but that alone does not help. The plugin is very strict with comparing the host.

**Comment by zlugg** [comment]
> @zlugg Yes, I agree, I wouldn't set it up with [www](http://www). But in this case, the web-site's URL with www exists since 1997, and I would not want to change that. Wordpress seems to do the redirect from non-www to www automatically.

A 301 redirect does not have any negative SEO effects. While you're at it do a 301 redirect from http to https which have a positive effect on at least googles ranking.

**Comment by nichu42** [comment]
We have a redirect from http to https, of course.
I appreciate your efforts to convince me to use WordPress on the root domain, but it's not me who is against it. I know that I initially wrote about SEO, but this is also true: The management will rather skip Fediverse integration than seeing a different URL in the address bar.

So, my question to @pfefferle remains: Would be possible to have an option to operate wordpress-activitypub on the root domain?

**Comment by pfefferle** [comment]
There is always an option, but it requires me to add some changes and you, to also tweak your hosting env a bit. If your handle will be `name@company.com` instead of `name@www.company.com`, WebFinger will search at `https://company.com/.well-known/webfinger` and that means that `company.com` has to support SSL and either redirects to `www.company.com` or you have to manually add some htaccess rules to `company.com` that will rewrite requests to `www.company.com`.

So if you are not able to do some of these changes, it would not help if I add support of that to the code. Just to clearify that up front ;)

**Comment by nichu42** [comment]
I'd be happy to do the .htaccess changes, but company.com does support SSL and redirects to www.company.com already, so that shouldn't be necessary. But thanks for the warning.

**Comment by nichu42** [comment]
Cool, thank you very much @pfefferle! 👍

**Comment by nykula** [comment]
Does this feature still work? After moving a blog to WordPress and installing this extension, the blog account appears using the `example.org@www.example.org` format, with `www` visible in the domain on Blog Profile page and in the actual profile as visible on Mastodon.

**Comment by nykula** [comment]
It seems to me that in [get_webfinger](https://github.com/Automattic/wordpress-activitypub/blob/6f06fd33092713511b993a0ca99c3798b04a34b2/includes/class-application.php#L110) a call to [normalize_host](https://github.com/Automattic/wordpress-activitypub/blob/6f06fd33092713511b993a0ca99c3798b04a34b2/includes/functions-url.php#L50) was lost during some refactor, is that possible? I'm not very familiar with the codebase, though, so I don't know if it should be there or in some other place.
