### ISSUE TITLE
webfinger is leaking email address

### ISSUE THREAD

**Issue by shleeable** [pfefferle/wordpress-activitypub#291]
https://shlee.fedipress.au/.well-known/webfinger?resource=acct:shlee@shlee.fedipress.au

![image](https://user-images.githubusercontent.com/17537000/224875784-bac1d43a-0c23-4b95-af40-ca36c1b1b3de.png)

Can we remove the email? It ain't required.

**Comment by pfefferle** [comment]
@shleeable I would recommend to re-create the issue on the WebFinger plugin repo.

**Comment by shleeable** [comment]
created https://github.com/pfefferle/wordpress-webfinger/issues/26
