### ISSUE TITLE
Preserve formatting?

### ISSUE THREAD

**Issue by YuriGal** [pfefferle/wordpress-activitypub#298]
Is it possible to preserve formatting of the original WordPress post?

E.g. [this one](https://codecorner.galanter.net/2023/03/24/enable-activitypub-plugin-on-bitnami-wordpress-instance-with-letsencrypt/) uses syntax highlighting for the code snipped, but it is lost when the post is shown on a Mastodon instance.

**Comment by timnolte** [comment]
Mastodon doesn't natively support such formatting. So this isn't really a plugin issue but a Mastodon issue.

**Comment by mediaformat** [comment]
Luckily Mastodon [will support rich text](https://github.com/mastodon/mastodon/pull/23913) in an upcoming release.
> Add native support for the incoming tags: del, pre, blockquote, code, b, strong, u, i, em, ul, ol, li
Transform h1 through h6 tags to `<p><strong>contents</strong></p>`

**Comment by timnolte** [comment]
So I should probably have notes that we should be careful about not having tunnel vision with Mastodon. ActivityPub is not just a Mastodon thing and we should be looking at the ActivityPub specifications so that the plugin works with the entire Fediverse.

**Comment by pfefferle** [comment]
That is what I am trying and that is why the WordPress Plugin supports a lot more html elements 😊

**Comment by pfefferle** [comment]
I will close this issue, because it seems no plugin issue! Please re-open if you think differently.
