### ISSUE TITLE
Password-protected posts are federated.

### ISSUE THREAD

**Issue by alisinfinite** [pfefferle/wordpress-activitypub#30]
As in the title: password-protected posts from WordPress are being publicly federated, including content and images.

From my point of view, more "expected" behaviors would be either that password-protected posts:

- aren't federated
- are federated, but with only placeholder content (i.e. "this post is password-protected", etc.)
- are federated but with some sort of security group permissions (if possible?).

Or possibly add a configuration option to allow a user to select from the above?

**Comment by pfefferle** [comment]
Oops, sorry for that! Will remove the publication on the first version and think about your ideas!
