### ISSUE TITLE
Checks all passing, posts not appearing

### ISSUE THREAD

**Issue by jszym** [pfefferle/wordpress-activitypub#306]
Hi,

I install ActivityPub on a wordpress install (gortyn.jszym.com), ensured the Webfinger and Author page checks went through, and made two test posts afterwards.

While I'm able to find @admin@gortyn.jszym.com and it correctly shows the number of posts, I can't see any of the posts (still not there a day later).

Site Health indicates that wp-cron is working. I'm not seeing anything ActivityPub specific using WP-Control (not sure if I should).

![wpcontrol](https://user-images.githubusercontent.com/1421301/233692879-f0d25e35-a581-4f9a-8771-4b5df96e72cf.png)

I'd really appreciate it if I can get a few hints on how best to debug this sort of thing. Let me know if you need any more information.

Much Thanks,
JS

**Comment by pfefferle** [comment]
Have you published some posts after following your blog profiles? Mastodon does not request old posts :(

**Comment by jszym** [comment]
Oh awesome it works!! I read the disclaimers about posts made before activating ActivityPub don't show up, but I didn't realise that I wouldn't see them unless I followed. Very cool! Thanks so much.
