### ISSUE TITLE
Can't be found on Mastodon, but Webfinger didn't show error

### ISSUE THREAD

**Issue by orangpelupa** [pfefferle/wordpress-activitypub#315]
Webfinger https://webfinger.net/lookup/?resource=vrse%40vrse.my.id

It didn't say any error. But the user and posts can't be found on Mastodon.

The activitypub plugin has been activated and setup before posts were published under that user

The posts under that user https://vrse.my.id/author/vrse/

**Comment by pfefferle** [comment]
I could follow you on Mastodon with no problems.

![Bildschirmfoto 2023-05-01 um 19 55 58](https://user-images.githubusercontent.com/2373/235501483-00801cd4-69b0-44cf-83d5-f8bdb2e5719c.png)

**Comment by orangpelupa** [comment]
Thank you. I Just checked and yes it now appear. Weird. Maybe caching issue somewhere in my setup.

Case closed.
