### ISSUE TITLE
How do I accept a follower?

### ISSUE THREAD

**Issue by ealgase** [pfefferle/wordpress-activitypub#32]
I've attempted to follow the admin user of my blog, but on Mastodon it says it's awaiting approval.  Is this a known issue, and is there a way to fix this?

**Comment by pfefferle** [comment]
You shouldn‘t have to accept followers, the plugin should do this automatically. Can you send me the identifier/blog-url, so that I can try to reproduce it?

**Comment by ealgase** [comment]
Sure.  I'm trying to follow @admin@kila.rocks (it's a website of a landowners association).  I'm trying to follow on linuxrocks.online, a Mastodon instance.

What I've noticed is that it adds me as a follower initially, but when I make a new post on Wordpress, it goes to "awaiting approval".

**Comment by pfefferle** [comment]
Sorry, but I can't reproduce your problem:

![bildschirmfoto 2019-02-23 um 16 31 23](https://user-images.githubusercontent.com/2373/53288465-95cf9500-3788-11e9-8a4e-2d541de28608.png)

Can you have a look at your settings, if I am listed as a follower. If so, it might be a problem of the mastodon-instance you tried to use?!?

**Comment by ealgase** [comment]
What instance are you on?  I could try to reproduce it there.

**Comment by pfefferle** [comment]
Mastodon.social

**Comment by ealgase** [comment]
Ah, I can't sign up there.

Anyway, I've found that it initially succeeds, but if you reload in ~1 or 2 hours, it'll go to the "awaiting approval" status.

**Comment by pfefferle** [comment]
I tried it also on linuxrocks.online and it also seems to work... if it changes the status 1 or 2 hours later, perhaps you should contact the admin of the instance...

![bildschirmfoto 2019-02-24 um 09 26 47](https://user-images.githubusercontent.com/2373/53296984-9f074300-3816-11e9-827c-6805bcc82baf.png)

**Comment by pfefferle** [comment]
I re-checked my account (3 hours later) and it still looks fine. Perhaps a glitch or a caching problem?

**Comment by ealgase** [comment]
Hmm, ok.  I'll try on some other instances and see if there's still an issue.  Thanks for your help.

**Comment by pfefferle** [comment]
@ealgase have you used another ActivityPub plugin, like Pterotype before? Perhaps a caching issue?

**Comment by ealgase** [comment]
No, I haven't.  It's started working for me now, too.

**Comment by pfefferle** [comment]
Weird, but fine if it works finally 😊

**Comment by timnolte** [comment]
@pfefferle so this seems to have started for me again. I do have LiteSpeed cache setup as well as I have my own Mastodon instance running version 3.5.3. it initially says that my Mastodon account is following (Unfollow) but then after a minute then a refresh it changes to Follow Requested. I am running WordPress 6.0 and I know there were caching performance updates made in 6.0 that I've seen cause problems. I'm not sure what else to check on. I'm the admin of Mastodon instance and I don't have any problems following others.

**Comment by timnolte** [comment]
> @pfefferle so this seems to have started for me again. I do have LiteSpeed cache setup as well as I have my own Mastodon instance running version 3.5.3. it initially says that my Mastodon account is following (Unfollow) but then after a minute then a refresh it changes to Follow Requested. I am running WordPress 6.0 and I know there were caching performance updates made in 6.0 that I've seen cause problems. I'm not sure what else to check on. I'm the admin of Mastodon instance and I don't have any problems following others.

So I figured out my issue was actually LiteSpeed & ModSecurity rules that we're throwing 403 permission denied errors upon Follow requests. After updating my ModSecurity rules to allow the `application/activity+json` content type things were working correctly. I had to believe this was something with my current hosting setup as I had followers listed in WordPress.

**Comment by mediaformat** [comment]
@timnolte Glad you solved it! 

Is there any config lines you could share, for a FAQ, or health check?
