### ISSUE TITLE
Description/main account

### ISSUE THREAD

**Issue by azbulutlu** [pfefferle/wordpress-activitypub#33]
As these users are essentially one way feeds, it would be great if the feeds when viewed from fediverse could have 

1) an icon
2) a description (e.g. this would be especially useful to point out that this is a wordpress install that cannot follow back or boost, and a brief description of the blog)
3) information slots (similar to up to 4 slots mastodon has.  this would be very useful to add custom information mastodon account associated with this blog)

Unless the plan is to have these eventually work as full fledged actors that can follow, boost and comment on other accounts? although these features would be useful even in that case.

Thanks for this great plugin!

**Comment by pfefferle** [comment]
I am not sure I get you right, but all the points you mentioned are already implemented.

![bildschirmfoto 2019-02-24 um 09 31 27](https://user-images.githubusercontent.com/2373/53296998-fd342600-3816-11e9-92e5-5782bba50555.png)

The plugin uses the avatar of the user as icon, the description of the user as description and the links for the slots...

**Comment by azbulutlu** [comment]
My mistake for missing this. :) I didn't think to try user settings of wordpress. Thank you for quick comment.

**Comment by pfefferle** [comment]
no problem :)

let me know if you still miss something.

**Comment by azbulutlu** [comment]
ok here is one issue I am noticing and one enhancement that would be useful if feasible. (https://www.azbulutlu.org/author/azbulutlu_tgtrrc/ being the guinea pig for this experiment) 

1) the avatar (from local media file) doesn't show when using a plugin (I use https://www.azbulutlu.org/wp-admin/plugin-install.php?tab=plugin-information&plugin=simple-local-avatars not sure if there is one that happens to be compatible with this addon) to replace gravatar which is a privacy issue.

2) This is a fairly minor issue but it would be nice to be able to customize which of these links. Right now there is 3 static categories. With the exception of website these are predetermined domain that repeats itself. it would be nice if
a) i was possible to hide any existing information (e.g. only have "blog" in my case)
b) being able to have custom slots as "key":"descriptor" pairs (similar to the way it is on mastodon. This would allow customizing these slots to have information that matches use case of the person using the site. (e.g. I'd like to use a link to my main mastodon, and link to my main website as "portfolio". Another person might want to link to their rss feed, and put a pronoun and email information in publicly, etc) 

Again thank you for the great work on this addon.

**Comment by lapineige** [comment]
Could we configure the avatar manually ?
In my case my account as no avatar, but it's a single user blog, and I would like to use for instance the blog logo.
I guess this can be linked to #43, but it would be even more convenient to be able to configure it ourselves.
