### ISSUE TITLE
Proper tagging on upper case vs lower case

### ISSUE THREAD

**Issue by chrisaldrich** [pfefferle/wordpress-activitypub#34]
Not quite sure what may be causing it, but I've noticed on my site that I get a properly tagged #WCSCV but don't get it properly tagged when I use lower case #wcscv. Is this to be expected or something in the line of a regex issue?

Examples: [[1](https://boffosocko.com/2019/02/22/call-for-speakers-wordcamp-santa-clarita/)] [[2](https://boffosocko.com/2019/02/23/55744466/)]

(Originally posted at https://boffosocko.com/2019/02/27/proper-tagging-on-upper-case-vs-lower-case/)

**Comment by pfefferle** [comment]
Hmm, interesting... It is definitely no regex problem... Have you added the #tag on post-creation or have you added the #tag afterwards (post edit)?

**Comment by pfefferle** [comment]
And btw. the GitHub post shows that it should work in general: https://boffosocko.com/2019/02/27/proper-tagging-on-upper-case-vs-lower-case/ :)

**Comment by chrisaldrich** [comment]
I noticed the last part myself and had wondered if it was the period following the hashtag. 

I think I've tested the #tag on both post-creation and post edit and not seen problems with either. (This particular case was initially seen on post-creation, but I've also played with it using post edit since and see the same issue.)

I'll also note that for example 1, if I put the hashtag on a new line, it wraps/links properly, but when it's on the same line with just one space between the prior sentence it doesn't. If I add two spaces between the sentence and the hashtag it also wraps/links properly.

Perhaps it's a quirk with TinyMCE Advanced, which is the editor I happen to be using? I'll try to test that out later, but thought I'd point out the edge case.

Since discovering that two spaces will fix the issue, feel free to close this.

**Comment by pfefferle** [comment]
Any news on this?

**Comment by pfefferle** [comment]
@chrisaldrich friendly ping ;)

**Comment by chrisaldrich** [comment]
Didn't seem to be TinyMCE, so I'm not sure what could be causing the difference. Feel free to close this for now. I'll reopen if I see other edge cases or behavior which may be relevant.

For those interested in manually **preventing** the automatic hashtag behavior in some cases I'll note that adding things like a zero-width space `&#8203;` between the # and the tag text seems to be useful. I'm sure there are other similar methods...
