### ISSUE TITLE
Posts stopped being broadcasted after February 15

### ISSUE THREAD

**Issue by 5teveroy** [pfefferle/wordpress-activitypub#36]
The last post from my WordPress blog that is visible from Mastodon is from February 15th. I have made a few more posts since then and they are not visible. I’m keeping the plugin updated. I don’t remember making changes to the site and nothing jumps out at me in the config.

Site: https://micro.steveroy.ca
Plugin version 0.5.1

**Comment by 5teveroy** [comment]
They seem to have resumed now. There is a hole where a few posts didn't make it through, but the last two worked. Closing.

**Comment by pfefferle** [comment]
I am working on a "resend" feature. Should be part of the next release.
