### ISSUE TITLE
Blog in a subpath / webfinger test fails

### ISSUE THREAD

**Issue by lapineige** [pfefferle/wordpress-activitypub#37]
My wordpress is installed in domain.tld/subpath.
When I try to test the webfinger part, it fails. With both username@domain.tld ("invalid content-type: text/html") and username@domain.tld/subdomain (<- this one gives me an encoding error "invalid URL escape "%2F"").

Is this plugin compatible with subpath ?

**Comment by pfefferle** [comment]
WebFinger does not support subdirectories, so you have to create a `.htaccess` file in your root and forward the request to your blog directory.

**Comment by lapineige** [comment]
And for Nginx ? What rule should I use ?

**Comment by celesteh** [comment]
> WebFinger does not support subdirectories, so you have to create a `.htaccess` file in your root and forward the request to your blog directory.

An example file would be extremely helpful.

**Comment by lapineige** [comment]
How can I use that rule with Nginx ?

**Comment by lapineige** [comment]
I tried with `rewrite ^/.well-known/ ^/subdirectory/.well-known/ last;`.
It doesn't work. I have this error (using https://client.webfinger.net/lookup) `invalid content-type: text/html`.
And it tries to connect to : `https://domain.tld/.well-known/webfinger?resource=acct%3Ablog%40domain.tld`

**Comment by lapineige** [comment]
I'm wondering : I tried to do that change in nginx config file for my wordpress, not for the root domain.
But I need to change the root domain, right ?
So when webfinger tries to access domain.tld/.well_known, it redirects to domain.tld/blog/.well_known ?

**Comment by pfefferle** [comment]
exactly!

**Comment by lapineige** [comment]
He doesn't work, same error, text/html content :(

**Comment by lapineige** [comment]
Ok I fixed this problem: I was due to Yunohost SSO, which were blocking any public access to this file.

Now the redirection is working.

Here is the solution:
```
location /.well-known/ {
        return 301 https://$server_name/YourSubFolder/$request_uri;
}
```

https://client.webfinger.net shows the json.

But I still can't see my blog from Mastodon.

**Comment by pfefferle** [comment]
Can you give me your identifier?

**Comment by lapineige** [comment]
Search for lapineige@lapineige.fr

**Comment by pfefferle** [comment]
Two things:

* You are redirecting your profile URLs https://lapineige.fr/wp/blog/author/lapineige/ to the main URL, but they are required for ActivityPub! Perhaps you use YoastSEO?
* I am not sure if mastodon supports http redirects

**Comment by lapineige** [comment]
> You are redirecting your profile URLs https://lapineige.fr/wp/blog/author/lapineige/ to the main URL, but they are required for ActivityPub! Perhaps you use YoastSEO?

Uh… that's not on purpose… No I don't use this plugin.

> I am not sure if mastodon supports http redirects

It works for Nextcloud.

**Comment by pfefferle** [comment]
But what/who is redirecting your profile pages?

**Comment by lapineige** [comment]
I don't know…

**Comment by lapineige** [comment]
Ok I found the plugin (NinjaFirewall) that was changing the default behaviour.

But now the WebFinger tool gives me a 403 forbidden (as before my rewrite).
But if I try to connect to the URL it tries to reach, the redirection is working…

**Comment by pfefferle** [comment]
Can you try to refresh the permalinks of your blog? go to the permalinks page and simply press the save button... you do not have to change anything...

**Comment by lapineige** [comment]
Done, same result.

**Comment by lapineige** [comment]
So here is the current status: the redirect works on the browser. With `curl`, it shows a 301. With `curl -L` it follows the redirect and I have a 403.

**Comment by lapineige** [comment]
Ok, in fact a wordpress upgrade changed my nginx config (I use it with Yunohost).
I fixed that.
It works :slightly_smiling_face: - even if I can't see the blog posts (the number is correct on the profile) but I guess it needs time to federate.

Problem solved, thanks :)

**Comment by celesteh** [comment]
Hi, I appreciate that you don't want to keep issues open when the solution is known, but has this actually been documented any place else but in these issues?  

I'd do a pull request, but it doesn't seem like the README is the best location and  other help files are not immediately obvious.

**Comment by lapineige** [comment]
Well I didn't want to spam again @pfefferle with my problems ^^

I don't know where to put this, I'm actually writing a blog post (in French) to talk about this plugin, but my problem was kind of specific and I don't know if it's a good idea to explain the solutions in a place where it's hard to find, while here in the issues it's kind of easier to found it.

**Comment by pfefferle** [comment]
If you can also write an English version I can add it to the faq section of the readme...

**Comment by lapineige** [comment]
That's an idea… I will see if I have some time to do it, then I'll give you the link :)

**Comment by lapineige** [comment]
After sometimes, I discovered that my nginx config changed, and I'm not sure I kept the previous one.

I tried to reconfigure it, with
```
location /.well-known/ {
        return 301 https://$server_name/subfolder/$request_uri;
}
```

But it doesn't work from Mastodon and https://webfinger.net/lookup/ gives me this: 
>  Error getting JRD: 400 Bad Request

A `curl https://domain.tld/.well-known` gives a 301 Moved Permanently, which is normal (it should redirect to `https://domain.tld/subfolder/.well-known`).
But a `curl -L https://domain.tld/.well-known/` gives a 404, a `curl -L https://domain.tld/.well-known/webfinger` a :
> {"code":"rest_missing_callback_param","message":"Missing parameter: resource","data":{"status":400,"params":["resource"]}

And `curl -L https://domain.tld/subfolder/blog/author/pseudo/` a :
> {"code":"activitypub_unsupported_resource","message":"Resource is invalid","data":{"status":400}}

I'm lost, I don't remember which URL I should test, and how to configure Nginx…

**Comment by pfefferle** [comment]
The URL you have to check is `https://domain.tld/.well-known/webfinger?resource=acct:username@domain.tld`

**Comment by pfefferle** [comment]
> {"code":"rest_missing_callback_param","message":"Missing parameter: resource","data":{"status":400,"params":["resource"]}

This error is correct! It says, that your rewrite seems to work, but you pass no resource param.

**Comment by pfefferle** [comment]
Here a working example: `https://notiz.blog/.well-known/webfinger?resource=acct:pfefferle@notiz.blog`

**Comment by lapineige** [comment]
https://webfinger.net/lookup/?resource=https%3A%2F%2Fnotiz.blog%2F.well-known%2Fwebfinger%3Fresource%3Dacct%3Apfefferle%40notiz.blog 404 not found 😅

**Comment by lapineige** [comment]
For my domain, I have a 400 bad request and `{"code":"activitypub_unsupported_resource","message":"Resource is invalid","data":{"status":400}}`

**Comment by lapineige** [comment]
If I try with an article from my wordpress (the last one, that doesn't appear on mastodon): `422 Validation failed : text can't be blank`

**Comment by lapineige** [comment]
Ok now instead of using `https://$server_name/YourSubFolder/$request_uri;` (https://github.com/YunoHost-Apps/wordpress_ynh/issues/61#issuecomment-490521823) I replaced $server_name with the actual `domain.tld`, and now `https://domain.tld/.well-known/webfinger?resource=acct:username@domain.tld` works.
But I can't see my article on mastodon.

**Comment by pfefferle** [comment]
Can you post some real URLs, so I can check them?

**Comment by pfefferle** [comment]
Is it the URL from your GitHub profile? If so, it does return the JSON response but without content.

Request:

```
curl "https://lapineige.fr/wp/blog/2020/04/retour-dexperience-sur-le-format-dimage-webp-un-excellent-rapport-qualite-poids/" \
     -H 'Accept: application/activity+json'
```

Response:

```
{
  "@context": [
    "https:\/\/www.w3.org\/ns\/activitystreams",
    "https:\/\/w3id.org\/security\/v1",
    {
      "manuallyApprovesFollowers": "as:manuallyApprovesFollowers",
      "PropertyValue": "schema:PropertyValue",
      "schema": "http:\/\/schema.org#",
      "value": "schema:value"
    }
  ],
  "id": "https:\/\/lapineige.fr\/wp\/blog\/2020\/04\/retour-dexperience-sur-le-format-dimage-webp-un-excellent-rapport-qualite-poids\/",
  "type": "Note",
  "published": "2020-04-28T16:15:58Z",
  "attributedTo": "https:\/\/lapineige.fr\/wp\/blog\/author\/lapineige\/",
  "summary": null,
  "inReplyTo": null,
  "content": null,
  "contentMap": {
    "fr": null
  },
  "to": [
    "https:\/\/www.w3.org\/ns\/activitystreams#Public"
  ],
  "cc": [
    "https:\/\/www.w3.org\/ns\/activitystreams#Public"
  ],
  "attachment": [],
  "tag": []
}
```

Do you use a pagebuilder or a multi language plugin?

**Comment by lapineige** [comment]
Thank you.
I don't think I use any pagebuilder, and I don't use a multi-language plugin…
It was working a few months ago, I didn't test it in the mid-time…

**Comment by pfefferle** [comment]
Hmmm... I just tested it with my site and it seems to work properly:

```
curl "https://notiz.blog/2020/03/15/i-am-a-human-of-wordpress/" \
     -H 'Accept: application/activity+json'
```

Also when I search for the URL on mastodon.

**Comment by lapineige** [comment]
EditorsKit and Stackable, that I used to add more blocks, are not in the pagebuilder category, right ?

**Comment by lapineige** [comment]
Ooooook that's super weird: I tried to change Activity-Object-Type (I changed a random parameter), saved it, then disabled an enabled again the extension, and while curl still fails, I can see it with the URL on Mastodon…

**Comment by pfefferle** [comment]
:blush:
