### ISSUE TITLE
Demo/Test server?

### ISSUE THREAD

**Issue by drequivalent** [pfefferle/wordpress-activitypub#38]
Is there any demo or test server for this plugin that I can test the federation on?

**Comment by pfefferle** [comment]
A test server that runs WordPress and the plugin or a test-server of Mastodon/Pleroma/...?

**Comment by drequivalent** [comment]
A test server that runs WordPress with this plugin and several users and articles on it.

**Comment by pfefferle** [comment]
There is no real test-instance, but the plugin does not really change anything in your wordpress installation, so it super easy to run some tests and reinstall it if it does not fit your needs.

**Comment by mediaformat** [comment]
@drequivalent 
You could make a temporary WP installation from https://jurassic.ninja 

1. Add wordpress-activitypub
2. Add some dummy content with [fakerpress](https://wordpress.org/plugins/fakerpress/)
3. And test federation...
