### ISSUE TITLE
Customizable length of excerpts or an option to just publish the headline of an article

### ISSUE THREAD

**Issue by stefangrotz** [pfefferle/wordpress-activitypub#40]
It would be great If there would be a way to customize the length of the excerpt or an option to just publish the headline of the post plus a link.

**Comment by pfefferle** [comment]
If you select "The full content." and the "WordPress Post-Format", it will post the title and the link for articles. Does that work for you, or do you need a "The title" as settings option.

**Comment by lapineige** [comment]
It doesn't do it for me: I would like to present the article title and a link to it.

> If you select "The full content." and the "WordPress Post-Format"

Then I have the first line of the article, and a "Read more" resul that is broken (on mastodon, I see the ≤a href …» then the actual link).

**Comment by arthurlutz** [comment]
I would also be a user of a custom length (400 seems a bit long for my timeline)
