### ISSUE TITLE
Convert paragraphs to break lines

### ISSUE THREAD

**Issue by stefangrotz** [pfefferle/wordpress-activitypub#41]
When I publish a long text with many paragraphs on wordpress it gets published as on long block on mastodon. It would be great if paragraphs would be converted into line breaks.

**Comment by asgartech** [comment]
@stefangrotz, it may be a problem with your settings. I have my site set to post the full content as a "Note".

[This post](https://www.matthewgraybosch.com/2019/04/09/hello-again-world/) has paragraphs and subheadings. The paragraphs render properly [when propagated to Mastodon](https://mastodon.sdf.org/web/statuses/101897546887135855) but not the subheadings.

**Comment by pfefferle** [comment]
@asgartech is correct. If you want to have paragraphs, you have to select "The full content." and "Note". This should work best with most of the plattforms.
