### ISSUE TITLE
[Question] Cannot reply to comments from website

### ISSUE THREAD

**Issue by asgartech** [pfefferle/wordpress-activitypub#42]
This may be similar to #39.

My WordPress installation with the current wordpress-activitypub plugin is capable of *receiving* replies to posts, and can also accept DMs and mentions unrelated to posts on the site.

However, I cannot reply from the website to comments on posts. Nor can I reply to DMs and mentions. Is this functionality on the roadmap?

**Comment by pfefferle** [comment]
Yes, this is definitely on my Roadmap!

**Comment by asgartech** [comment]
Thanks! I'm looking forward to it.

**Comment by albjeremias** [comment]
i can do it! you can close :tada:
