### ISSUE TITLE
allow the whole blog to be one actor

### ISSUE THREAD

**Issue by schiessle** [pfefferle/wordpress-activitypub#43]
I can think about many WordPress instances where not the bloggers but the blog as such are the most important thing most people want to follow. For example thing about a blog for your local soccer club. Sometimes "User A" might blog about the latest game, sometimes "User B", etc. But for me this doesn't matter. I don't want to follow all the individual bloggers and keep track if a new user starts to write blogs for my soccer club. I just want to follow the soccer club's blog and get all the news. In such a case it would be good to have a "meta actor" which is the whole blog I can follow and not only the authors as individual actors.

**Comment by manoelnascimento** [comment]
I agree. There are situations where bloggers prefer to maintain a collective identity without presenting themselves as individual authors. Is this possible?

**Comment by sunjam** [comment]
I like the way Pterotype allows you to have @blog@yoursite.com + set a profile pic and description for the fediverse so it appears as a user.

**Comment by Cambridgeport90** [comment]
I'm for this, as well. Particularly on community sites that join the Indieweb.

**Comment by terenc3** [comment]
I worked on this today and was able to find my blog via mastodon. If nobody is working on it i like to continue to test if the posts work and sumit a pull request

**Comment by pfefferle** [comment]
@terenc3 sure, that would be awesome!

**Comment by mkljczk** [comment]
I know a few people that would install this plugin if only this feature was available

**Comment by wilenius** [comment]
Hi, any further plans on developing this feature? I think it would be really useful. Implementing this is sadly beyond my skills, but I can volunteer to test this. @terenc3 were you able to implement a working version of this feature?

**Comment by wilenius** [comment]
Also, isn't this practically the same feature request as #1?

**Comment by pfefferle** [comment]
Yes, thats why this one is closed ;)

Yes, it is still planned as a feature!
