### ISSUE TITLE
no posts visible

### ISSUE THREAD

**Issue by vsatmydynipnet** [pfefferle/wordpress-activitypub#44]
Hi,

thank you for this cool plugin. I have the problem that i can follow my WP user via Mastodon, see the count of his posts, profile image. can also mention the user, which shows up as comment to no post But i do not see the posts in Mastodon user view. Can you tell me how to debug the following stuff:

Things not working:

- i do not see the posts in mastodon profile view

- i followed the account from external-mastodon-user-1 and it showed up in the wp-activitypub-dashboard. I unfollowed the user there and the user still shows up as follower. I followed the user with external-mastodon-user-2 (different instance that user1) and this user is not listed in the wp-activitypub-dashboard  , there is still user1. BUT on mastodon it shows things correct

To mention:

I run the age-check plugin, so maybe there should be an custom bot exception done by me.

**Comment by vsatmydynipnet** [comment]
Looked further:
...../.well-known/webfinger?resource=acct:......
works fine

**Comment by vsatmydynipnet** [comment]
correction:
the follower problem is reduced to not deleting a follower.

was my fault, i followed admin user, then unfollowed him. but the follower is still there, so not deleted.

fault was, i transfered posts to another user, followed this one. in the admin dashboard this one is invisible,  which is ok. so its only not deleted if unfollow happens

**Comment by vsatmydynipnet** [comment]
manually deleted "activitypub_followers" from usermeta db for this user

**Comment by vsatmydynipnet** [comment]
requesting:
wp-json/activitypub/1.0/users/5/outbox
shows the posts, so access is fine. at least looks to me fine. different mastodon server requests this now and get arounf 346K data back, which should be ok. size to them is same as manually requesting it.

it shows 65 posts on mastodon for this user, bu no posts in posts view.

any idea how to further debug this?

**Comment by pfefferle** [comment]
Have you published a new post after you followed your blog? Mastodon does not import old posts, so it only shows the posts after it was first followed by someone on the server.

**Comment by vsatmydynipnet** [comment]
Oh boy :-) ....... Thank you!
