### ISSUE TITLE
Activitypub account requires follow request approval

### ISSUE THREAD

**Issue by Cambridgeport90** [pfefferle/wordpress-activitypub#47]
I have the latest verrsins of both wordpress and the plugin, and when I look at the account that is created (cambridgeport90@cambridgeport90.net), I see that the two people following me have to be approved. How do I either approve these requests or set this to not require follow approval? Thanks!

**Comment by pfefferle** [comment]
It seems that there was/is an error with creating the "publicKeyPem".

**Comment by pfefferle** [comment]
I will close this in favor of https://github.com/pfefferle/wordpress-activitypub/issues/31

**Comment by Cambridgeport90** [comment]
Is there a quick way I can fix that? And how did you discover that? I would have never known where to look.

**Comment by pfefferle** [comment]
Working on the plugin there was a lot of "trial and error" because the public key mechanism is not part of the spec, but a mastodon specific thing, so I know where to look at ;)

Up to now, my focus was to have a plugin that works with most ActivityPub servers, but now I have to clean up a lot of things and work on UX/UI. I will add a method to check sever-requirements and checks for the most known issues.

**Comment by pfefferle** [comment]
In detail:

```
curl "http://cambridgeport90.net/author/cambridgeport90/?resource=acct:lapineige%40lapineige.fr" \
     -H 'Accept: application/activity+json'
```

This returns the porfile JSON with an empty `publicKeyPem` key.

**Comment by Cambridgeport90** [comment]
So do I need to add that into one of the plugin files?

**Comment by pfefferle** [comment]
No, there is no quick fix yet, sorry 😞

I hope I can implement the requirements-check asap, so that you will be able to check if you can use the plugin on your current Webhosting or not.

Von meinem iPhone gesendet

**Comment by Cambridgeport90** [comment]
I’ll be checking updates; I do that about once a week, more if prompted, so, not worried about that. Thanks, though!
