### ISSUE TITLE
Can't see my toots on Mastodon

### ISSUE THREAD

**Issue by MaiaDereva** [pfefferle/wordpress-activitypub#48]
Hello Matthias,

thanks a lot for this great plugin! :)

I can see my account here: http://maiadereva.net/author/maia/
and there: https://mamot.fr/web/accounts/206070
without any problem.

But the toots don't appear in Mastodon :thinking: 

I published a new post after I followed my blog but nothing appears.

Do I miss something?

Cheers
Maïa

**Comment by lapineige** [comment]
If you enter one article URL in the search bar, it doesn't show up ?
edit: just tested, it doesn't work.

For my wordpress I had to enter the URL of an article to finally see it on mastodon, as well as on the website profile.
(I suppose the federation takes time ? :thinking:)

**Comment by pfefferle** [comment]
* Have you published a post after you followed your profile on mastodon?
* ActivityPub uses WP-Cron to federate new posts. Have you enabled WP-Cron?

**Comment by MaiaDereva** [comment]
Hello @pfefferle 

- Have you published a post after you followed your profile on mastodon? : **yes**
- Have you enabled WP-Cron? **Now yes, and I published a new post, but nothing appears on Mastodon**

**Comment by pfefferle** [comment]
@MaiaDereva can you see a list of followers in the AP settings?

**Comment by MaiaDereva** [comment]
@pfefferle : yes I see 4 followers including you :)

**Comment by MaiaDereva** [comment]
If it can help to make a diagnosis: I noticed that I've modified the avatar, description and public name of the user but they didn't change on Mastodon

**Comment by MaiaDereva** [comment]
Hi Matthias,

avatar, description and public name of the user have been modified if I have a look here : https://mastodon.xyz/web/accounts/319528
but not here : https://mamot.fr/web/accounts/206070
Both of them leads to http://maiadereva.net/author/maia/ if I click on the avatar via Mastodon.
I don't understand...

And still no toots visible :(

**Comment by pfefferle** [comment]
It seems to show toots now, is this still a problem?

**Comment by MaiaDereva** [comment]
Hi Matthias,
yes,  there is still a problem, see here: https://mastodon.xyz/web/accounts/319528
The total number of toots is correct, but I don't see any toot in the profile. Do you?

**Comment by Cambridgeport90** [comment]
I am having the same issue, here, on https://cambridgeport90.org, as well. If you follow cambridgeport90@cambridgeport90.org, you won't find me. I tried searching myself, and that's how I discovered that there was an issue at all. For kicks, as well, I looked up https://cambridgeport90.org/author/cambridgeport90 on webfinger.net, and the resulting log gives a 400 bad request error message (see the full error message copied into my post called "current IndieWeb glitches")

**Comment by pfefferle** [comment]
@Cambridgeport90 Your profile/author URLs are not available, which is necessary for the plugin to work. The author page redirects to the main page. Maybe you use YoastSEO or something similar, that forces this redirect.

**Comment by Cambridgeport90** [comment]
You hit the nail right on the head. I do use Yoast. Will removing that plugin fix the error? Or is there a way I can work around it by forcing a profile page in the IndieAuth settings?

**Comment by pfefferle** [comment]
Hey @Cambridgeport90 you do not have to disable the plugin completely. There is a setting somewhere, that disables the feature. Perhaps I should overrule the setting and disable it via the AP plugin in the future. I will have a look, if I can point you to the setting. Give me a sec.

**Comment by pfefferle** [comment]
@Cambridgeport90 you find the setting here: SEO -> Search Appearance -> Archives -> Author archives settings -> Author archives -> Enabled. I hope this solves your problem.

**Comment by Cambridgeport90** [comment]
Awesome!
