### ISSUE TITLE
cannot find page

### ISSUE THREAD

**Issue by transfluxus** [pfefferle/wordpress-activitypub#5]
@licci-core@licci.eu
https://licci.eu/author/licci-core/

I'm using wp 5.0.2
php56 (I think)
cPanel

**Comment by mitchellurgero** [comment]
Page loads for me:

![image](https://user-images.githubusercontent.com/4168998/50365420-20520900-053a-11e9-98b1-49330784754d.png)

**Comment by transfluxus** [comment]
yes, but can you find it in mastodon?

**Comment by transfluxus** [comment]
Thanks for the advice. how do I do that? Is that a nginx thing? I don't have root access. Tried to install your webfinger plugin, didn't help.
Danke! :)

**Comment by pfefferle** [comment]
try to simly hit save on the permalinks settings page.

**Comment by pfefferle** [comment]
@transfluxus does that help? https://github.com/pfefferle/wordpress-activitypub/issues/8

**Comment by pfefferle** [comment]
yes, but this should be generated by WordPress... Have you enabled "pretty permalinks"?

**Comment by transfluxus** [comment]
permalinks were set to **Post name**
I set them to **Custom Structure** with `/%postname%/`. 
reinstalled... still not found
(trying from Pleroma now as well)

**Comment by transfluxus** [comment]
can you just send me the file in the meanwhile :D

**Comment by transfluxus** [comment]
a .htaccess file that I would put into the .well-known folder. I don't. something that identifies the wp account for mstdn and other

**Comment by pfefferle** [comment]
You have a .well-known folder?

**Comment by transfluxus** [comment]
yes

**Comment by pfefferle** [comment]
is that created by your webhoster? for let's encrypt?

**Comment by transfluxus** [comment]
yes with autoconfig/mail but only folders, no files (at least no visible ones)

**Comment by noplanman** [comment]
I'm running into this on a client server, which has a `.well-known/acme-challenge` folder automatically created by the hosting for the LE verifications.

Permalinks are refreshed but the path still searches directly in the file system it seems, obviously giving me a 404.

Is there a specific .htaccess rule I can add to perform some selective rerouting?
Or do you have any other idea?
