### ISSUE TITLE
Mentions to the account appears in the comments

### ISSUE THREAD

**Issue by lapineige** [pfefferle/wordpress-activitypub#50]
When someone write a toot from Mastodon, mentioning the blog account, it appears in the admin comment section (I don't know if it goes in any article of the website).

*NB : This include private toots, which is a privacy issue.*

If it's not a reply to an article/comment, this should not be included.
Or maybe as a "contact form", by receiving an email ?

**Comment by lapineige** [comment]
I tried to answer to some mention (not a comment), and it's impossible, I have a red box with `-1` inside.

**Comment by pfefferle** [comment]
Yes, this is a bug. I save an image with no post and that might cause some errors. I will fix it in one of the next updates.

**Comment by gytisrepecka** [comment]
Maybe in options there could be a setting to assign such comments to particular page?

Let's say someone on fediverse mentions my WordPress user `@gytis@inretio.dev` - currently such post arrives at website's comments without any post assigned. If a setting could automatically assign it to, say, `inretio.dev/mentions`, all of those mentions could be nicely listed as this page comments.

**Comment by dshanske** [comment]
We have that in the webmentions plugin. I wonder if both could use the same setting
