### ISSUE TITLE
Feature request : ability to remove&republish a post

### ISSUE THREAD

**Issue by lapineige** [pfefferle/wordpress-activitypub#52]
# Problem
When an article is published, a status is published too.
And in some cases (depending on the blog config'), there is the tittle and/or resume with it.

But if we want to edit the tittle, or the content (for instance to correct spelling mistakes), the status won't change.

# Solution

Add the ability to "republish" the status.
For instance a button in the article page to remove & publish again the status.

**Comment by pfefferle** [comment]
The plugin sends an update action if it was edited, as defined in the AP spec. Have you acknowledged some issues with mastodon?

**Comment by lapineige** [comment]
My post are not updated when I see them from Mastodon.
(nor deleted)

**Comment by pfefferle** [comment]
Does Mastodon support editing of posts? Maybe it is a Mastodon issue?

**Comment by pfefferle** [comment]
Here is the part of the sepc: https://www.w3.org/TR/activitypub/#update-activity-outbox
And here is the part in the code: https://github.com/pfefferle/wordpress-activitypub/blob/97505e527e2aac21d45f9ca43d35bc367b460581/includes/class-activitypub.php#L111

I may recheck if the code works properly thou.

**Comment by lapineige** [comment]
> Does Mastodon support editing of posts? Maybe it is a Mastodon issue?

It does not in the UI.
Maybe that means it doesn't allow it at all.

Then we have an issue :/
I don't think it would be allowed, cause that would allow some people to edit their post (which is not intended).
I'm not sure this can be fixed on Mastodon side…

Then would it be possible to add such a "Remove&Publish again" option in the plugin ?

**Comment by pfefferle** [comment]
> Then would it be possible to add such a "Remove&Publish again" option in the plugin ?

Sure, but that means, that I have to implements hacks because Mastodon does not support the full spec and that feels "hacky" :(

I will think about that point.

**Comment by lapineige** [comment]
A workaround would be to support deletion of articles that are removed (or converted to drafts, I mean not publicly accessible any more) #16 : then we could just set the article as draft, and publish it again.

**Comment by pfefferle** [comment]
Good idea... I will start to implement "delete" and we will have a look what is possible with that.

**Comment by pfefferle** [comment]
duplicate #16
