### ISSUE TITLE
Regex for hashtags is breaking CSS colour in widget

### ISSUE THREAD

**Issue by noplanman** [pfefferle/wordpress-activitypub#57]
I'm faced with the situation where a plugin adds custom CSS to a sidebar widget and the hashtag conversion wrongly sees the CSS colours as tags and converts them to tag links, resulting in code like this in the widget within the `<style>` tags:
```
background-color: <a href='https://domain.com/tag/123abc/' rel='tag'>#123abc</a> !important;
```

Should this plugin be manipulating the normal website output at all?
I would have expected to see changes like the hashtag conversion when the content gets accessed through an AP stream only, leaving everything untouched when accessed normally through a browser.

Is this expected behaviour?

Related issue #21

**Comment by pfefferle** [comment]
> Should this plugin be manipulating the normal website output at all?

No! It is only added to the `the_content` filter. I have no idea, why it is added to a sidebar widget.
