### ISSUE TITLE
Publish excerpt in content instead of summary

### ISSUE THREAD

**Issue by GidiKroon** [pfefferle/wordpress-activitypub#6]
I am very new at the fediverse and even newer at WordPress, so please forgive me if I misunderstand something.

I understood from the description of the excerpt functionality that it is to replace the content in case of length-restricted formats like an RSS feed. Such a feed should show the excerpt + a link instead of the content; if no manual excerpt is provided the actual content may be automatically shortened by such a feed to provide an excerpt.

This plugin (version 0.1.0) places the manual excerpt in the summary field instead. A recent commit actually creates an automatic excerpt from the content, and places that in the summary field. If I understand it correctly, the summary field is used in systems like Mastodon to provide the content warning.

I therefor propose to put the manual excerpt, or possibly the automatic excerpt if applicable, in the content of the activity stream, rather than the summary.

**Comment by pfefferle** [comment]
Thanks for your feedback, I was not aware of the `summary` usage of mastodon.social... I will run some tests and think about your suggestions!

**Comment by tobiasd** [comment]
As far as I know it is only Mastodon that uses the `summary` field as content warning. Friendica e.g. is using the `summary` field in AP when a posting contains an `abstract` BBCode element typed in by the author of a posting.
