### ISSUE TITLE
Author Page Span with H-Card and P-Author as string not tags

### ISSUE THREAD

**Issue by timnolte** [pfefferle/wordpress-activitypub#60]
On my author page the p-author & h-card span tag around my name is showing up as a string instead of an actual tag. The tag elements are actually encoded.

`&lt;span class='p-author h-card'&gt;Tim Nolte&lt;/span&gt;`

**Comment by pfefferle** [comment]
Please remove the microformats2 plugin

**Comment by timnolte** [comment]
@pfefferle that did in fact fix the problem, however, does this mean that the AP plugin is already adding the additional microformats2 support? Thanks!

**Comment by pfefferle** [comment]
No, ActivityPub does not require/support any kind of Microformats. Microformats are (only) needed for the IndieWeb stack.

**Comment by pfefferle** [comment]
To give a bit more context: https://github.com/indieweb/wordpress-uf2/issues/41

**Comment by pfefferle** [comment]
I will close this issue, because it is not related to the ActivityPub plugin
