### ISSUE TITLE
Akismet treats federated comments as spam

### ISSUE THREAD

**Issue by alexgleason** [pfefferle/wordpress-activitypub#62]
On blog.ninapaley.org, I've finally managed to get the posts available in the fediverse (yay!) but federated comments aren't coming through into WordPress.

Possibly related, but closed without resolve: #55

**Comment by alexgleason** [comment]
I've confirmed the comment is received. In `handle_create` I print the value of `$commentdata` and it looks like this:

```
6416 | Alex Gleason | https://spinster.dev/users/alex | <a href=\"https://blog.ninapaley.com/author/nina/\">@nina</a> test |  |  | 0 | Array
```

I haven't figured out whether calling wp_new_comment on it works yet. The comment is nowhere to be seen in the dashboard.

**Comment by alexgleason** [comment]
I printed `$status` and it gave me the comment ID. I looked up the comment directly and...

![Screenshot from 2019-09-07 22-39-12](https://user-images.githubusercontent.com/3639540/64482964-587ca300-d1c0-11e9-817f-0c710b02aee2.png)

**Comment by maste9** [comment]
Same here on plapperbu.de (commented from social.tchncs.de). Your issue brought me to look after Akismet spam directory and yes, there were the missing comments.

**Comment by DeadSuperHero** [comment]
Has anyone made progress with this? I've been considering moving over to `wordpress-activitypub` from `pterotype`, and running Akismet on the side to handle the constant influx of spam comments seems like the only way to go...

**Comment by pfefferle** [comment]
There is an open merge request: https://github.com/pfefferle/wordpress-activitypub/pull/66/

The question is: Is this the expected behavior (to set the comment on hold)?

**Comment by pfefferle** [comment]
@DeadSuperHero btw. I can also recommend https://wordpress.org/plugins/antispam-bee/ as an alternative to akismet.
