### ISSUE TITLE
Timezones

### ISSUE THREAD

**Issue by alexgleason** [pfefferle/wordpress-activitypub#63]
A post is made from a WordPress site where the system time is set to UTC-5: Chicago.

It reaches the Fediverse server, which stores time in UTC-0.

The timestamp is 5 hours off when displayed in the user's local time.

**Comment by pfefferle** [comment]
But isn't that a bug of the Fediverse Server then?

ActivityPub specifies `published` here: https://www.w3.org/TR/activitystreams-vocabulary/#dfn-published

It has to be `xsd:dateTime` which defines:

> The time zone may be specified as Z (UTC) or (+|-)hh:mm. Time zones that aren't specified are considered undetermined.

http://books.xmlschemata.org/relaxng/ch19-77049.html

**Comment by silksow** [comment]
I can confirm this issue with posts from my WP to mastodon.social

**Comment by jgoerzen** [comment]
Observed as well here

**Comment by pfefferle** [comment]
Fixed by #107 

Thanks @mediaformat !!
