### ISSUE TITLE
Activitypub / Profile Grid Conflict

### ISSUE THREAD

**Issue by FlophouseSam** [pfefferle/wordpress-activitypub#69]
Hi there,

I have built a Wordpress website using Profile Grid and have recently added ActivityPub in order to publish the unrestricted content to followers on the Fediverse. However, I am unable to find my profile/site from within Mastodon. When I navigate to the appropriate .well-known/webfinger address in my browser to check the resource, I find that the code there includes the address of the associated Profile Grid profile page ( ending in /my-profile\/?uid=13 ) rather than the address of the associated wordpress author page as I believe is required.

I consulted a friend online, who said the following...

"From what I can see, ActivityPub plugin uses WordPress's built-in function get_author_posts_url I'm guessing that ProfileGrid somewhere intercepts that function call and rewrites it to use its own profile link."

Is there a work-around for this?

It may also be worth mentioning that while some of the content on the site (including each Profile Grid profile page) is restricted to logged in members, the author page I'm currently trying to follow in Mastodon displays just fine to unregistered site visitors. 

All help greatly appreciated!

Many thanks,

Sam

**Comment by pfefferle** [comment]
Puuh... This is a hard one 😳

I have no idea of a simple "work-around" yet. But I will think about a solution.

**Comment by FlophouseSam** [comment]
Thanks Matthias. Much appreciated. Would be a shame to start over but I am keen to include federation at some level. I should mention that when users of my site post user blogs they are able to set privacy levels, determining whether their post is visible only to logged in members, friends on the site, or visible to everyone.

Technically, as every user has an associated identifier, Activity Pub should Federate their unrestricted posts. I can see that there is a User Blogs check box in the settings to allow for this. I'm not sure how this extra level of permissions might affect things but thought I should mention it.

Look forward to hearing your suggestions.

Many thanks,

Sam

Sent from ProtonMail mobile

-------- Original Message --------
