### ISSUE TITLE
Only url on mastodon

### ISSUE THREAD

**Issue by nicolascluz** [pfefferle/wordpress-activitypub#7]
Salut, since 4 days, i have got some problems with mastodon, the post url was display without content (or just picture with). 
I updated from here (since 0.0.2), and releases between 0.0.2 to 0.1.0 worked without problems

**Comment by pfefferle** [comment]
I added post-type support... and this is how mastodon handles `articles` because they might be longer as the supported characters. If you use `aside`, `status` or `note` it will still post the whole post. Is this ok for you or should I add a setting to enable/disable `post-types`, to force „always“ the `note` type?

**Comment by nicolascluz** [comment]
Making some test , bookmark with note type
(like here https://mabulledu.net/17854-2/ ), but mastodon didn't display right, just the last line

**Comment by pfefferle** [comment]
Du you use post-kinds?

**Comment by nicolascluz** [comment]
yep, 3.0.9 with some modification , because <section> doesn't display content on mastodon. Worked fine with activitypud.

**Comment by pfefferle** [comment]
For your understanding: Version 0.0.2 was a combination between OStatus and ActivityPub. I switched to 100% ActivityPub with version 0.1.0 that’s why you see the changes. If you use post-kinds, the bookmark stuff is not really part of the post-content, but added via a filter and this filter seems to not be loaded in my implementation. I will have a look how to load all filters outside of WordPress‘ `the_loop`.

**Comment by Suitbert** [comment]
Just recognized, that an edit / update of an old Wordpress post in my blog will send a ActivityPub message, containing the date of the first time publishing (and link and photo). That confused me a little bit. Maybe ignore those updates and only transfer new posts? What do you think?

**Comment by pfefferle** [comment]
I am open to both... I implemented "update" because this is how Webmentions work, but if ActivityPub/Mastodon do not really support update, I can remove the feature or make it customizable.

**Comment by Suitbert** [comment]
Great! I would prefer to have it customizable. Maybe we could have it like this:

[x] new posts
[ ] post updates
[ ] post comments

Just as an idea. Thanks a lot!
