### ISSUE TITLE
Mark private DM comments somehow

### ISSUE THREAD

**Issue by bekopharm** [pfefferle/wordpress-activitypub#72]
I recieved a comment via Mastodon that was in fact a DM (direct message) not intended to become a public comment. 

It was just not published because it's content suggested that the message was intended to be private so I didn't approve it in the moderation queue.

I'm aware that a "private" message in the context of `ActivityPub` is a hit and miss but without any hint that a comment was in fact a private DM there is no way to tell from the WordPress admin interface.

Mayhap a custom comment-type would help.

**Comment by bekopharm** [comment]
stale, huh?

**Comment by pfefferle** [comment]
Keep

**Comment by pfefferle** [comment]
Private messages are now ignored and will be not added to the comments section!

**Comment by lapineige** [comment]
Which means we can't be aware that someone mentioned us (our blog) ?
Couldn't they be placed as "awaiting approval" instead ? And maybe with some highlighting that this was private/a DM.

**Comment by pfefferle** [comment]
I would not do that ("awaiting approval"), because the risk is too high, that it will be approved by accident. What about sending the message via E-Mail?

**Comment by lapineige** [comment]
Yeah that's another option :)

**Comment by pfefferle** [comment]
@lapineige would you like to file a new issue for that?
