### ISSUE TITLE
Add title at the beginning of the toot

### ISSUE THREAD

**Issue by arthurlutz** [pfefferle/wordpress-activitypub#74]
First off, kudos for a great wordpress plugin ! 

Would it be possible to have an option where the title appears at the beginning of the toot  ?

**Comment by arthurlutz** [comment]
hi! closed as in "wontfix" or "already fixed" ?

**Comment by pfefferle** [comment]
I fixed it in the master... but I have to tweak some more things for another release...

It is now possible to customize the activity, using template-tags.
