### ISSUE TITLE
Articles with embedded images render incorrectly in federated view

### ISSUE THREAD

**Issue by DeadSuperHero** [pfefferle/wordpress-activitypub#77]
Tested this on Friendica, so I'm not sure whether other fediverse platforms supporting the `Article` activity type necessarily have this problem.

Basically, I have several articles containing images. When fetching said articles through Friendica, I've noticed that the images seem to have been stripped out of their positions in the post, and re-attached to the bottom of it. What's more confusing is that the image count seems to be limited to 3, even if I have far more embedded images in the blog post.

Original Article: https://deadsuperhero.com/2019/10/my-favorite-failed-game-projects/

Friendica Output: https://libranet.de/display/5722ea150a8a9db82fa7905af48253dba2eabbe0

Granted, this could just be a problem with Friendica and how it deals with HTML coming from WordPress, I'm not totally sure yet. But I thought I'd log this here to let you know.

**Comment by pfefferle** [comment]
hmmmm... I strip them from the post and add the images as attachments... It is a shame that every AP network differs in the UI... :(
