### ISSUE TITLE
Comments from Hubzilla users don't show up in the comment section below posts

### ISSUE THREAD

**Issue by vanitasvitae** [pfefferle/wordpress-activitypub#79]
Hi!
I received some comments that do show up in the "recent comments" section on the dashboard. However, those comments are nowhere to be found below the post itself. Clicking "view comment" in the dashboard only brings me to the top of the post.

I noticed, that those comments all appear to come from Hubzilla users, so I suspect this is an issue related to Hubzilla comment processing?

**Comment by vanitasvitae** [comment]
I believe there is something broken with hubzilla. Among the comments that I receive and that don't show up properly as explained above, I also seem to receive comments that are unrelated to my post.

**Comment by pfefferle** [comment]
Hm, I might have broken comments completely... I will have a look!
