### ISSUE TITLE
Cannot follow

### ISSUE THREAD

**Issue by techmagus** [pfefferle/wordpress-activitypub#8]
Hi,

When I'm trying to follow via Mastodon, I keep getting an error "503Remote data could not be fetched". If I try via Pleroma, it doesn't see the website. If I try in Osada and Hubzilla, same thing as Pleroma.

Here are some examples:
```
@laibcoms@gameshogun.xyz (PHP7.0; nginx; solo installation)
@laibcoms@snoworld.one (PHP7.2; nginx; multisite installation)
```

Is there an installation step I should've done?

I have the ActivityStream, WebFingers, /.well-known/, Webmention plugins. Tried disabling the /.well-known/ plugin but still the same. I also removed the OStatus plugin in case there are overlaps/conflicts.

Thank you!

**Comment by pfefferle** [comment]
I get an error for your webfinger endpoint https://client.webfinger.net/lookup?resource=laibcoms%40snoworld.one

**Comment by pfefferle** [comment]
You have to check your rewrite rules and/or use the author URLs instead of the webfinger identifier

**Comment by techmagus** [comment]
Hi,

Thanks! I took another look and I finally found it. It turns out I have to add ?$args in try_files for the /.well-known redirect (although for Wordpress itself it is fine with just /index.php so I followed that format initially).

```
location ~* /.well-known {
  try_files $uri $uri/ /index.php?$args;
}
```

The webfinger works now and the json file is showing in via the webfinger.net lookup tool (thanks for the link!) I can follow now without the 503 error (on Mastodon's side) and in Osada as well as Hubzilla. However, Pleroma still can not find it (probably on their side already?)

There were also a few cases wherein I had to use the author URL before the WebFinger worked, probably some cache from the AP sites I tested on.

Thank you again!

**Comment by gytisrepecka** [comment]
Thanks! I am running one instance of WordPress on Nginx (as HTTP server, not just reverse proxy) and adding below to configuration solved issue.

`
location ~* /.well-known {
   try_files $uri $uri/ /index.php?$args;
}
`
Now I can find WordPress users from fediverse clients.

Before adding above configuration users were not found even though I allowed access to .well-known (dot files are not allowed by [default WordPress template for Nginx](https://wordpress.org/support/article/nginx/)) - it would give this error:
`code     rest_missing_callback_param`

**Comment by danicotillas** [comment]
@gytisrepecka @pfefferle Where should I add that code?
`location ~* /.well-known { try_files $uri $uri/ /index.php?$args; }`
I read abut the .well-known folder but I couldn't know where to add that line of code.

Thanks for a Laynman's explanation!

**Comment by pfefferle** [comment]
It has to be placed inside you nginx config. I am not an NGINX expert, but I think it has to be placed in the nginx.conf .

**Comment by danicotillas** [comment]
> It has to be placed inside you nginx config. I am not an NGINX expert, but I think it has to be placed in the nginx.conf .

Ok, that's why. I can't access to that as I'm using a Siteground server but I'll ask them if there is any way to do it.
Thanks!

**Comment by danicotillas** [comment]
@pfefferle Apparently Siteground uses Apache server and only Nginx for the cache. I have uninstalled the cache method and clean up everything. It stills shows up the error. Also I get this message from the wordpress health:

Your WebFinger endpoint https://comunicacionabierta.net/.well-known/webfinger?resource=acct:danicotillas@comunicacionabierta.net does not return valid JSON for application/jrd+json.

any clue? Thanks

**Comment by pfefferle** [comment]
hmmm... It seems that this is no 404 error caused by WordPress, so WordPress does not load at all... :(

Can you try to reset your permalinks (hit save on the permalinks site) and re-check it?

**Comment by danicotillas** [comment]
Done...and nothing.
Maybe because they are /%year%/%monthnum%/%postname%/ ?

**Comment by gytisrepecka** [comment]
> @gytisrepecka @pfefferle Where should I add that code? `location ~* /.well-known { try_files $uri $uri/ /index.php?$args; }` I read abut the .well-known folder but I couldn't know where to add that line of code.
> 
> Thanks for a Laynman's explanation!

This is specifically for NGINX to be placed inside `server` block (something like `VirtualHost` on Apache).

Notice `.well-known` has a dot (`.`) in the beginning - typically web servers block access to files with dot in the beginning of file name to prevent exposing of `.htaccess`, `.htpasswd` and other files. Therefore you might need to explicitly allow access to `.well-known`.

Check your web server access log - if "access denied" is there, will need to allow access to `.well-known`.
