### ISSUE TITLE
Replys on Mastodon are somehow broken

### ISSUE THREAD

**Issue by deponeWD** [pfefferle/wordpress-activitypub#86]
Replys from Mastodon are returning without webmention data. The content of the reply is displayed in the backend, webmention data is empty as well as the emails.

**Comment by bekopharm** [comment]
Replies looks fine for me: http://php.microformats.io/?url=https://beko.famkos.net/2020/02/21/58768/

What I'm missing are Shares and Likes. Was this ever implemented? I don't think so.

I got some but they are all via bridgy.

**Comment by pfefferle** [comment]
I have not implemented shares and boosts yet...

**Comment by dioraman** [comment]
Relates #96 .

**Comment by okpierre** [comment]
Would like to see comments and replies working with this plugin. Is there a timeline for this @pfefferle ?

**Comment by mediaformat** [comment]
@okpierre I've started a pull request #95 which I'm actively working on, the scope of which includes federating replies from wordpress to the fediverse.
