### ISSUE TITLE
Unable to reply to article from mastodon

### ISSUE THREAD

**Issue by PhieF** [pfefferle/wordpress-activitypub#89]
Hi

I'm trying to reply to an article and have it as a comment on my article, but it doesn't appear

here is what I see in wordpress apache logs

172.23.0.4 - - [06/May/2020:23:37:48 +0000] "POST /wp-json/activitypub/1.0/users/1/inbox HTTP/1.1" 403 7245 "-" "http.rb/4.3.0 (Mastodon/3.1.2+glitch; +https://masto-instance.me/)"

even if I have

/activitypub/1.0/users/(?P<user_id>\d+)/inbox

in my list of routes
any ideas ? 

Thanks for your wonderful work !

**Comment by PhieF** [comment]
Found it, WP SpamShield is the culprit... sorry

**Comment by tyrosinase** [comment]
WPBruiser also blocks it with "Token not submitted," FWIW. No way to whitelist sites in that, so I'll be changing spamblockers.
