### ISSUE TITLE
Blacklist Functionality

### ISSUE THREAD

**Issue by michaeljamesdunn** [pfefferle/wordpress-activitypub#90]
I'm not sure if this is an issue or not, but I'm wondering about the actual behavior of the blacklist setting. I have a handful of instances added, however I still have a follower from one of them (and I also see that particular instance's crawler showing up in my nginx access log). I'm just wondering if  that's expected behavior.

**Comment by pfefferle** [comment]
The blacklist function does not block crawlers, it only denies follow request from the listed servers. It only blocks servers from the moment you added them to the list. If someone from one of these servers was on your followers list before, he/she will not be blocked. I am working on a feature, where you will be able to edit your followers list, to remove them by hand.

If users from blocked servers will still be able to follow you, it is a bug!

**Comment by michaeljdunn** [comment]
The follower I'm referring to is from Gab, which of course is in the list by default (and I haven't removed it at any point), so perhaps. Thanks for the clarification.
