### ISSUE TITLE
Add Post-Content: Title + Content

### ISSUE THREAD

**Issue by xuv** [pfefferle/wordpress-activitypub#91]
As of now, the plugin offers 3 options for Post-Content:

- Title and link
- Excerpt
- Content

The first two invite the reader to quit their preferred Fediverse interface and visit the WP site. While the third one allows the reader to get the whole content of the WP article (without the title) within the comfort of their Fediverse software interface.

I believe not sending the title of the article could, for some people, be a mistake. A fourth option could then be proposed with **Title and content**, which would send the whole article and its title through as an AP message.

_I've only tested this from a Mastodon instance. Maybe other AP software don't have that issue of a missing title._

**Comment by pfefferle** [comment]
I will add the possibility to customize the content of an activity with placeholders, like in the permalinks structure, so that you will be able to customize the content, like you want.
