### ISSUE TITLE
[Mastodon] Comments, Likes, Reposts as Replies, Favourites, Boosts (and vice versa)

### ISSUE THREAD

**Issue by dioraman** [pfefferle/wordpress-activitypub#96]
**Steps to reproduce**

1. Search (--at--) pfefferle (--at--) notiz.blog
2. Click account
3. Click any toot
4. CTRL-Click the date time
5. Compare the toot in Mastodon and the post in Wordpress
6. [Reply, fav, and boost the toot in Mastodon]

**Actual result**
Mastodon does not track interactions in Wordpress as comments, likes, reposts.
Wordpress does not track interactions in Mastodon as replies, favourites, boosts.

**Expected result**
Wordpress comments, likes, and reposts are seen in Mastodon as replies, favourites, and boosts. Mastodon replies, favourites, and boosts are seen in Wordpress as comments, likes, and reposts.

**Note**
This is a missing core feature to steer adoption of the plugin by Wordpress blogs close to Mastodon instances.

**Comment by okpierre** [comment]
I'm interested in giving this plugin a try. @dioraman has there been any progress with matching comments/replies with the fediverse?

**Comment by paulo-roger** [comment]
Hi, this is why comments from Mastodon doesn't show in wordpress?
