### ISSUE TITLE
Excerpt contains non-paragraph text 

### ISSUE THREAD

**Issue by GidiKroon** [pfefferle/wordpress-activitypub#98]
This may be hard to fix for the same reason as #9, but just in case you find a way:

If you use '`excerpt`' as post-content option and your post has paragraph blocks, image or gallery blocks with captions, embed blocks, etc, I would expect only the paragraph blocks to be used for the automatically  generated excerpt. Now everything is lumped together and generates some weird fediverse posts.

Assume you write a short blog post saying "_This is some difficult stuff!_" and include a picture of Einstein with caption "_Albert Einstein_". Then the fediverse post is "_This is some difficult stuff! Albert Einstein_", as if you're quoting him...

I would only expect captions to be included if a post-content option allows for the full html to be published and if images remain inline.

**Comment by hirusi** [comment]
> or you should better use the full content.

That is what I'm using:

![image](https://user-images.githubusercontent.com/3974019/119260330-fbbd5800-bbef-11eb-949a-5b65a0bd38a9.png)

Yet the post came out like this:

![image](https://user-images.githubusercontent.com/3974019/119260359-17286300-bbf0-11eb-889e-adb6cd737dba.png)

Original WordPress post:

![image](https://user-images.githubusercontent.com/3974019/119260406-4212b700-bbf0-11eb-95b3-4e7252c8606b.png)

Am I missing something or getting something wrong?

**Comment by GidiKroon** [comment]
You are trying to see a post with full rich content on Mastodon, but Mastodon doesn't support this since it can't show rich text. You should see how it looks on Pleroma on Friendica, since these platforms do support a fully formatted post. I have tried to load your example post in my Pleroma and Friendica, but I didn't succeed for reasons I don't know yet.

I'm thinking that for best compatibility with Mastodon, we should either use the excerpt option (and avoid using captions for now), or use the full content as you've done, but also set the post type to "Article" instead of "Note". This way Mastodon will show only a title with link, and Pleroma and Friendica will show the full post.

**Comment by hirusi** [comment]
@GidiKroon That's very helpful context as well as recommendations, thank you so much! 😊
