### ISSUE TITLE
TAGS generates from #hashtags break the website layout

### ISSUE THREAD

**Issue by rebelcode-xr** [pfefferle/wordpress-activitypub#99]
While I was editing an article I noticed weird stuff like this popping up in several places/pages:
![image](https://user-images.githubusercontent.com/63522951/93405091-54cc3380-f88c-11ea-9873-a72925dc6cea.png)

After a bit of debugging I figured out that was the AP plugin and especially this option:
![image](https://user-images.githubusercontent.com/63522951/93405178-9957cf00-f88c-11ea-8b47-db45ae351a3e.png)

The cause seems to be #hashtags or color codes in the text areas:
![image](https://user-images.githubusercontent.com/63522951/93405261-d4f29900-f88c-11ea-9e7a-c06ff94a9161.png)

It might be correlated to this other issue: https://github.com/pfefferle/wordpress-activitypub/issues/57

**Comment by pfefferle** [comment]
ok, perhaps I have to optimize my Regex! Can you share a link with such color codes, so I have a reference I can test against?

**Comment by rebelcode-xr** [comment]
that's just an example, it can be: **#whatever**

**Comment by pfefferle** [comment]
@rebelcode-xr yes sure, but this is how it should work, so I search for examples that are wrongly discovered as tags 😉

**Comment by rebelcode-xr** [comment]
> @rebelcode-xr yes sure, but this is how it should work, so I search for examples that are wrongly discovered as tags 😉

ohhh, now I understand, so maybe is better to turn it off by default or ask the user before enabling it: I think filling WP with so many tags is a pretty personal decision to make 🤔

**Comment by rebelcode-xr** [comment]
another idea could be create a separated menu only for AP tags, like other plugins do:

**EVENTS MANAGER**
![image](https://user-images.githubusercontent.com/63522951/94260545-ac276f00-ff30-11ea-9da9-9d821e664114.png)

**Comment by pfefferle** [comment]
@rebelcode-xr there is no difference between activitypub-tags and "normal" tags. The architecture of this plugin is a bit different than the one of pterotype. There is no copy of all the activities within wordpress. The AP plugin tries to reuse as much as possible of the native WordPress infrastructure.

**Comment by rebelcode-xr** [comment]
> @rebelcode-xr there is no difference between activitypub-tags and "normal" tags. The architecture of this plugin is a bit different than the one of pterotype. There is no copy of all the activities within WordPress. The AP plugin tries to reuse as much as possible of the native WordPress infrastructure.

I understand that, the WP infrastructure is actually the same, just you differentiate tags generated by the user and tags generated by the plugin (like Events Manager separates events posts/tags/categories using WP logic/tables/functions): it's just easier to keep things in order from my point of view. but maybe I miss something.
